### ISSUE TITLE
Problem when switching from Conventional to Autonomy

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#101]
Right now there is a problem in the initialization. this due to the fact that I want to keep this model as a plugin to easily use it on other models!

@LAAP if you want to play with the model, the reinit need to be made "by hand now" by pressing "i" (like init) on the CoronaMap window

I'll try to fix that at some point but it's a kind of hard to fix bug

**Comment by LAAP** [comment]
Awesome @agrignard , I will try to iniciate with "i"

**Comment by LAAP** [comment]
@agrignard , I think this has been implemented with the "tag" of "Autonomy", I will close it

**Comment by agrignard** [comment]
no i think it's still there. I will check this

**Comment by agrignard** [comment]
This is link with #118 ( press on ````i  ````to initiate the pandemy)
