### ISSUE TITLE
People Behavior

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#102]
Right now the behavior is very simple as it was to illustrate a static map. We can complexify it but we need to be sure why as it will also complexify the story telling and the visualization.

2) Visualizing working/life behaviour. We can start with a simple 3 types of people: People that works from home, people working in the office, people working in shops. All the agents has 5 time steps:

-People that works from home: Home - Home - Shopping - Home - Home
-People working in the office: Home - Work - Shop - Work - Home
-people working in shops: Home - Shop - Shop - Shop - Home

**Comment by agrignard** [comment]
First version of the 3 profile (people are commuting but they don't stay in the shop/office, etc) this is the next step (again it will change the clarity of the model but I will try to see how it looks)

<img width="1873" alt="Screenshot 2020-05-06 at 11 54 57" src="https://user-images.githubusercontent.com/3928502/81164374-8b19ae00-8f90-11ea-8e9f-5d6b4365abf2.png">

**Comment by LAAP** [comment]
Hi @agrignard ,

This is fantastic!!! Regarding movement; I am agnostic about people staying at the work or home. I have to run it and see the "feeling of it". However, now that Quarantine people will be staying at home, Maybe that already tells/changes the story... Not sure... The stay at the "building" can be just few "cycles" (5 cycles, for instance). So the agent stays 5 cycles, "dancing inside" of a "building" as soon as it touch it, and after jumps into the next step...

Regarding the colors, I suggest to keep red for infections. So maybe we can stick with a "pallet" of colors related with the "Land use of each profile": 

-HomeWorker: Bluish
-OfficeWorker: Yellowish
-ShopWorker: Orangish

**Comment by agrignard** [comment]
If you have a good palette for all the color, that can help. We start to have lots of color meaning different thing. we need design skills now for the color. Everything is a parameter.

If you give me some rgb i can easily put it

**Comment by LAAP** [comment]
Hi @agrignard ,

As you know, design is all about "testing". Also, as you know, the pallets change a lot when you "deploy it" in the design. So I we can try with:

-HomeWorker: (194,171,20)
-Home: (255,216,0)

-OfficeWorker: (3,129,166)
-Office: (0,195,251)


-ShopWorker: (192,104,40)
-Shops: (250,126,5)

**Comment by agrignard** [comment]
Why not
<img width="1249" alt="Screenshot 2020-05-06 at 22 13 50" src="https://user-images.githubusercontent.com/3928502/81223789-e24a6d80-8fe6-11ea-9ced-2e4a2bf208b1.png">

If you want to see the results you can change this part of the code 
`````
map<string, rgb> buildingColors <- ["residential"::rgb(255,216,0), "shopping"::rgb(250,126,5), "business"::rgb(0,195,251)];
`````
and
`````
map<string,rgb> color_per_type<-["homeWorker"::rgb(194,171,20),"OfficeWorker"::rgb(3,129,166),"ShopWorker"::rgb(192,104,40)];
`````

**Comment by LAAP** [comment]
@agrignard ,

I can't find the model with the new colors. Your last push in the Github says that wa smade 14h ago. Please, push it again

**Comment by agrignard** [comment]
Practicing my design skills ;-) 
<img width="1920" alt="Screenshot 2020-05-07 at 09 53 07" src="https://user-images.githubusercontent.com/3928502/81268730-9af4c900-9048-11ea-9143-a9e35574294d.png">

**Comment by agrignard** [comment]
Using Grid design (inspired by @yasushisakai book)
<img width="1353" alt="Screenshot 2020-05-07 at 12 36 17" src="https://user-images.githubusercontent.com/3928502/81285283-97207100-905f-11ea-9568-141f56d59c5d.png">

**Comment by agrignard** [comment]
His version of people behavior is now implemented
