### ISSUE TITLE
Infectious process broken

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#104]
Due to many changes made today in link with #102 the infectious process is currently broken (shouldn't be hard to fix but I cannot find it right now)

**Comment by LAAP** [comment]
Ok. @agrignard , let me know when it is working again

**Comment by agrignard** [comment]
Ok so just so that you understand the issue. 

I am now georeferencing the world (so it will be easy to put the abstract city on any real city (Boston, Andorra, Lyon, etc). However it's a bit more complex than expect from the GAMA side (always this question of projection). So right now the COIVD Epidemy is blocked( which is a great news ;-) ) but as soon as the Epidemic restart it means that the model will be ready to be apply to any location in the world. I hope to have it fix today but let's see
