### ISSUE TITLE
Quarantine a specific district/community

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#105]
Hi @agrignard ,

I think that the quarantine concept in the model is good working as a %, However, I think that we need to implement a way to Quarantine, in a separate way districts (Kent's red circle around the district). So Quarantine, it is a combination of:

1) Keeping people at home (%)

2) Closing borders (red circule)

With this, you could keep people working with a close border, or people Quarantine with open borders, and a combination of the 2 measures

**Comment by agrignard** [comment]
Do you want ot be able to click on a district and quarantine it?

**Comment by LAAP** [comment]
@agrignard , YES!

**Comment by agrignard** [comment]
the technical concept is here, right clik on a district when you are in the autonomous scneario and you can quarantine /unquarantine it and see the red circle

<img width="672" alt="Screenshot 2020-05-18 at 17 42 01" src="https://user-images.githubusercontent.com/3928502/82232435-ea7fa280-992e-11ea-9505-3267c7ce3978.png">

Now the tricky question is:  what does it mean to put a district in quarantine?

Initially, you have 0.1 of the people (corresponding to the crossRatio) that goes from one distrcit to another ven in autonomous cities. Ones in quarantine what do we do, what happens to the guy that was living on district 1 and working in district 2 when district 1 is in quarantine?

**Comment by LAAP** [comment]
**Quarantine measures:** 
-Total stop of movement between districts
-All agents stay at home and only goes shopping in a slower cycle period (every 7 days)
-No working at office only online working (online working increases to 60%

**Comment by agrignard** [comment]
New iteration people are staying in there district (and do there normal life )and do not commute outiside. That could be actually the definition of putting an autonomous district in Quarantine?
<img width="1130" alt="Screenshot 2020-05-25 at 17 42 20" src="https://user-images.githubusercontent.com/3928502/82827369-2f678400-9eaf-11ea-8c77-c54a0689e960.png">

- Still to be done, the people that use to work or shop in this district shouldn't be abel to go there (not sure yet ho ti implement it though)
-All agents stay at home and only goes shopping in a slower cycle period (every 7 days)
-No working at office only online working (online working increases to 60%

**Comment by agrignard** [comment]
See #132
