### ISSUE TITLE
No differences between Autonomus_Covid and CityScope_Coronizer. Merge?

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#108]
Hi @agrignard ,

I can't see the difference  between Autonomus_Covid and CityScope_Coronizer. Should we Merge?

**Comment by agrignard** [comment]
If you look at the code this is not the same model. Coronizer is a plugin that can be use in other model (like a classic cityscope). With a dedicated ViralPeople species that mirros the people and implemnt an SIR on it
