### ISSUE TITLE
Integrate the Pandemic effect in the City Efficiency KPI

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#111]
@agrignard, 

The city efficiency seems to increase even when the pandemic is growing fast. Should we review the math?

**Comment by agrignard** [comment]
The epidemie is indeed not taken in account in the efficiency which is right now only the ratio between people working vs people transiting, so yes we should I guess include also the pandemic (however there is the pandemic level also for that?)

**Comment by LAAP** [comment]
Hi @agrignard , as explained in issue https://github.com/CityScope/CS_Simulation_GAMA/issues/90#issuecomment-624056004   This is how we can measure the indicator for "efficiency": 

"(...) **[efficiency]** ", in order to see how pandemic reduce working force and time as soon as they get sick. So the working time is 8h per day (40h week) and as soon as people gets sick, this can drop:

-Healthy: 8h of work
-Sick asymptomatic: 7h (because you do not feel 100%)
-Sick symptomatic: 4h (because probably some of them will work from home even when sick)
-Death: 0h
-Recovered: 8h of work"

**Comment by agrignard** [comment]
Ok good idea. I'll do it

**Comment by agrignard** [comment]
Need to fix #121 first

**Comment by agrignard** [comment]
Ok so we have the working forces now (between 0 and 1)

So the question is now how to we compute the city Efficienty knowing that we have 3 value here between 0 and 1

ratio of walk , ratio of transit and ratio of work

**Comment by LAAP** [comment]
@agrignard ,

Good question, what about?:

a) Maximum value of the ratio (1) is when all the population is Healthy = (8h of work) multiplied by (Total population)

b) The minimum value of the ratio (0) is when all the population is dead = (0h of work) multiplied by (Total population)

Anything in between will be the combination of population multiplied by the different profiles:

-Healthy: 8h of work
-Sick asymptomatic: 7h (because you do not feel 100%)
-Sick symptomatic: 4h (because probably some of them will work from home even when sick)
-Death: 0h
-Recovered: 8h of work"

So, we can normalize 0 and 1 to 0 and 100%, and that is what we show in the "energy bar" chart

**Comment by agrignard** [comment]
ok easy to do, but it means that we remove one of the KPIs we introduced initially that was about walking vs mass transit?

**Comment by LAAP** [comment]
Yes I know that we have change a bit the approach. However, I think that walking vs mass transit can be a new KPI... But not sure if it is that interesting as a KPI

**Comment by agrignard** [comment]
@imartinezl do you feel like giving a try to this one?

the actual code to plot the city efficiency KPIs is here in Autonomous_covid.gaml

``````
			graphics 'City Efficienty'{
			  float nbWalk<-float(length (people where (each.macroTrip= false)));
			  float nbMass<-float(length (people where (each.macroTrip= true)));
			  float spacebetween<-first(legend where (each.type="right1")).shape.height/2; 	
				 //CITY EFFICIENTY
			  point posCE<-{first(legend where (each.type="right1")).location.x- first(legend where (each.type="right1")).shape.width/2,first(legend where (each.type="right1")).location.y- first(legend where (each.type="right1")).shape.height/2};
			  	
			  draw "City Efficiency: " + int((nbWalk)) color: #white at:  {40+ posCE.x, posCE.y+40} perspective: true font:font("Helvetica", 20 , #bold);			  
			  draw rectangle(55,first(legend where (each.type="right1")).shape.height) color: #white empty:true at: {posCE.x, posCE.y + 2*spacebetween- first(legend where (each.type="right1")).shape.height/2};
			  draw rectangle(50,(nbWalk/100)*first(legend where (each.type="right1")).shape.height) color: #white at: {posCE.x, posCE.y + 2*spacebetween - ((nbWalk/100))*first(legend where (each.type="right1")).shape.height/2};
			  
			 
			 
			  float spacebetween<-first(legend where (each.type="right1")).shape.height/3; 	
			  float offsetX<-first(legend where (each.type="right1")).shape.width/4;
			  float offsetY<--first(legend where (each.type="right1")).shape.height/8;
			  draw rectangle(nbWalk,20) color: buildingColors.values[1] at: {offsetX+posCE.x+nbWalk/2,posCE.y+spacebetween+20+offsetY};
			  draw "Walk: " + with_precision(nbWalk/length(people), 2) color: buildingColors.values[1] at:  {offsetX+posCE.x,posCE.y+spacebetween+offsetY} perspective: true font:font("Helvetica", 20 , #bold);
			  draw circle(10) color: buildingColors.values[1] at: {offsetX+posCE.x-20, posCE.y+spacebetween-20+offsetY};
			  
			  draw rectangle(nbMass,20) color: buildingColors.values[0] at: {offsetX+posCE.x+nbMass/2, posCE.y+2*spacebetween+20+offsetY};
			  draw "Mass: " + with_precision(nbMass/length(people),2) color: buildingColors.values[0] at:  {offsetX+posCE.x, posCE.y+2*spacebetween+offsetY} perspective: true font:font("Helvetica", 20 , #bold);
			  draw square(20) color: buildingColors.values[0] at: {offsetX+posCE.x-20, posCE.y+2*spacebetween-20+offsetY};
			  
			  
			  int toalTheoreticalWork <- length(ViralPeople)*8;
			  int effectiveWork <- length(ViralPeople where each.is_susceptible)*8 + length (ViralPeople where (each.is_asymptomatic and each.is_infected))*7 + length (ViralPeople where (!each.is_asymptomatic and each.is_infected))*4 +length(ViralPeople where each.is_recovered)*8;
			  draw rectangle(effectiveWork/toalTheoreticalWork * length(people),20) color: buildingColors.values[2] at: {offsetX+posCE.x+effectiveWork/toalTheoreticalWork/2, posCE.y+3*spacebetween+20+offsetY};
			  draw "Working forces: " + with_precision(effectiveWork/toalTheoreticalWork,2) color: buildingColors.values[2] at:  {offsetX+posCE.x, posCE.y+3*spacebetween+offsetY} perspective: true font:font("Helvetica", 20 , #bold);			  
			}
``````

and the value to use to update the KPIs according to @LAAP proposal is here (this attribute are updated while the virus spreads) in CityScope_Coronizer.gaml

``````
	bool is_susceptible <- true;
	bool is_infected <- false;
    bool is_immune <- false;
    bool is_recovered<-false;
    bool is_asymptomatic<-true;
``````

**Comment by agrignard** [comment]
See #130
