### ISSUE TITLE
Speed of the simulation

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#113]
@agrignard ,

We use to have a slider for the speed of the simulation. that was good for debugging. Is it possible to have it back?

**Comment by agrignard** [comment]
done

**Comment by LAAP** [comment]
@agrignard ,

the "simulation step" speeds the process for a second, but then stops and goes in a slow motion....

**Comment by agrignard** [comment]
OK I see this is due to the automatic acceleration effect when there is the transaition between 2 states to reach quickly the steady state.
`````
	reflex updateStep{
		if(step > 1#sec){
			step<-step-1#sec;
		}
	}
````



I have to work on that it's mainly related to the step of the simulation which is right now to #1sec to have a realistic behavior in term of motion

Which one do you prefer

**Comment by agrignard** [comment]
Ok it's now fixed. you can play with the simulation of the speed and still get the acceleration effect during the transition

**Comment by LAAP** [comment]
Hi @agrignard , sorry to be intense and re-open this issue again but, Can we keep a stable speed without rebalancing into a normal speed. As a user, sometimes I want to run the model in different speeds because I try to understand different behaviours that emerge at different speeds and in long term periods of time. 

It was working  like that few days ago

**Comment by agrignard** [comment]
Ok I made a trade off. You can use the custom step and it will stay, I disabled the acceleration effect by  default but it can come back as it's a parameter in the visualization category.
<img width="309" alt="Screenshot 2020-05-19 at 14 37 31" src="https://user-images.githubusercontent.com/3928502/82327179-4e14d900-99de-11ea-9c6b-5e6436848866.png">
<img width="305" alt="Screenshot 2020-05-19 at 14 37 36" src="https://user-images.githubusercontent.com/3928502/82327183-4f460600-99de-11ea-9dce-2f6024a6b2f0.png">
