### ISSUE TITLE
Covid parameters doesn't work

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#114]
@agrignard ,

Most of the Covid parameters (sliders) can't be used

**Comment by agrignard** [comment]
It's disable by default (as those parameter should be fixed if it was given by an expert in COVID) if you want to play with it just put the parameter below disable to false

<img width="310" alt="Screenshot 2020-05-12 at 22 23 03" src="https://user-images.githubusercontent.com/3928502/81741661-2fbf5280-949f-11ea-9208-77b449b52871.png">

**Comment by LAAP** [comment]
@agrignard ,

Not really, the only slider that can be used is the "Nb recovery day"
![Captura de pantalla 2020-05-13 a las 16 35 21](https://user-images.githubusercontent.com/19315213/81862542-df480380-9537-11ea-8885-180ca335c394.png)

**Comment by agrignard** [comment]
switch the button to false! when it's true the parameter are disable ;-) if it bothers you we cna remove it it was just to show that this is some parameter that should be more or less constant (assuming we know them)

**Comment by LAAP** [comment]
Awesome!!!! No, this is perfect!
