### ISSUE TITLE
Fever charts Improvement

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#115]
@agrignard ,

I like the new "Energy bar charts", however, I miss a bit the "Fever charts". I think this setting, with the fiver charts in the side was good:

<img width="1440" alt="Captura de pantalla 2020-04-27 a las 14 39 37" src="https://user-images.githubusercontent.com/19315213/81742153-a5122f80-946d-11ea-82ba-e10edfd0c44d.png">

**Comment by agrignard** [comment]
Yes very easy to reput but it look hugly ;-)

**Comment by LAAP** [comment]
@agrignard , 

I see that this is one of the issues that I have asked to the GAMA expert in charged of Charts in Vietnam (I do not remember his name now). I say to him that it could be cool to have access to "play" with the "visual part of the Chart". Seems to me that it is still a "black box" isn't? If you give me something with "more parameters" I can try to tweak it:

![Captura de pantalla 2020-05-13 a las 16 59 17](https://user-images.githubusercontent.com/19315213/81865075-7498c700-953b-11ea-99dc65ed87656f8c.png)

**Comment by agrignard** [comment]
what do you mean by play?

**Comment by LAAP** [comment]
I can "tweak" the design, so it looks more beautiful. Like changing colors, font, shapes, etc.

**Comment by agrignard** [comment]
ah ok so there is a bunch of parameter and different stye of chart you can play with like color of the font, size, color of the curve etc.

See here the different facet to play with
https://gama-platform.github.io/wiki/Statements#chart

**Comment by LAAP** [comment]
Awesome! I will play with it and make a push request   ;)

**Comment by agrignard** [comment]
I will close this issue as it's not really an issue. It just need to be played with

**Comment by LAAP** [comment]
@agrignard I will reopen this. I want to keep it as a reminder for me for "playing" with the design of the fiver chart

**Comment by LAAP** [comment]
Hi @agrignard , how can I activate the visualization of the fever chart?

**Comment by agrignard** [comment]
Yes it's in comment (as Most of the time at least for now I don't use it to produce the slides)

Just uncomment this part in Autonomous_Covid_Community

``````
		 /*display CoronaChart refresh:every(#mn) toolbar:false {
			 chart "Population: " type: series x_serie_labels: "time" 
			 x_label: 'Infection rate: '+infection_rate + " Quarantine: " + length(people where !each.isMoving) + " Mask: " + length( ViralPeople where each.as_mask)
			 y_label: 'Case'{
				data "susceptible" value: nb_susceptible color: #green;
				data "infected" value: nb_infected color: #red;	
				data "recovered" value: nb_recovered color: #blue;
				data "death" value: nb_death color: #black;
			 } 
		}*/
`````

**Comment by LAAP** [comment]
@agrignard ,
How can I change the size of the dots in the fever Chart?:

![Captura de pantalla 2020-05-28 a las 9 37 59 (2)](https://user-images.githubusercontent.com/19315213/83150635-821c8800-a0c9-11ea-924d-74ad0d9c6e94.png)

I am following the instructions at:

s://gama-platform.github.io/wiki/Statements#chart

And say:

<img width="655" alt="Captura de pantalla 2020-05-28 a las 9 31 58" src="https://user-images.githubusercontent.com/19315213/83150787-b1cb9000-a0c9-11ea-8be8-6262a1878196.png">

So I did:

![Captura de pantalla 2020-05-28 a las 9 34 04](https://user-images.githubusercontent.com/19315213/83150831-c445c980-a0c9-11ea-9a09-d53e1f907099.png)

But doesn't work. CAn you give me the "lexic"?

Also, I have change the color of the axis

```````
axes: color rgb (100)

``````
But, I only changes the Main axes, not the secondary (they are still in blue)

Also, rgb some times, like in the axis, works with only one value, (1) or (100) and some times is working in the traditional way of 3 values (1,1,0).... Why? How can I translate the traditional (1,1,0) to the one value one?

**Comment by agrignard** [comment]
the synatx is ````style````not ````Style`````

`````style:dot````for instance

**Comment by agrignard** [comment]
````axes:#red```` seems to work no?

<img width="642" alt="Screenshot 2020-05-28 at 16 28 11" src="https://user-images.githubusercontent.com/3928502/83154295-40f39a80-a100-11ea-86cc-cbf9bd9e6dc3.png">

**Comment by LAAP** [comment]
@agrignard 

Thanks! Questions: 

**1) Style of the dots = scale of the dots:** With the 

````
style:dot

````
What I am trying to do is to change the radius or diameter of the dots... and it is not working...

![Captura de pantalla 2020-05-28 a las 11 29 17](https://user-images.githubusercontent.com/19315213/83161703-c5312800-a0d6-11ea-999f-be07092ae5a3.png)

**2) Axes color:** Yes, Changing the color works since the beginning  by using "#red", and also "rgb (1)", but not by using "rgb (1,10)":

<img width="194" alt="Captura de pantalla 2020-05-28 a las 11 12 09" src="https://user-images.githubusercontent.com/19315213/83161937-1214fe80-a0d7-11ea-9f09-89fadd7ffe73.png">

**3) Secondary axes color:** The issue with the color is with the secondary axes, they became "blue":

<img width="375" alt="Captura de pantalla 2020-05-28 a las 11 10 47" src="https://user-images.githubusercontent.com/19315213/83162173-65874c80-a0d7-11ea-95aa-2358f7f514da.png">

**Comment by agrignard** [comment]
1)  I am not sure we change the size of the dot (dot means you want to see dot , it's the style of the graph

2) ````color rgb (1,1,0)````is a wrong syntax in gama you have to put ````rgb(1,1,0)```` which will be very black 

3) Oops doesn't look that great. can you check in your Gama preferences what you have in the Displays->Chart? this is what I have 
<img width="1302" alt="Screenshot 2020-05-28 at 17 41 58" src="https://user-images.githubusercontent.com/3928502/83162834-9634a980-a10a-11ea-9ab0-b847b05a5ffc.png">

**Comment by LAAP** [comment]
@agrignard ,

thanks for the help, the sintaxis was crucial. 

So Issue 2 and 3 are solved. It was related to the color:

![Captura de pantalla 2020-05-28 a las 14 07 47](https://user-images.githubusercontent.com/19315213/83177262-bf464180-a0ec-11ea-9fef-546af247e35e.png)

Now, I am still in "pain" with the sides of the "dots, points...", or whatever is this thing:

![Captura de pantalla 2020-05-28 a las 14 09 41](https://user-images.githubusercontent.com/19315213/83177361-e8ff6880-a0ec-11ea-9859-ae5bc9a434e1.png)

Any suggestions?

**Comment by agrignard** [comment]
Ok it already looks better in term of design 

Do we want to see this point? maybe no point (not sure if it's possible) would looks better

**Comment by LAAP** [comment]
@agrignard ,
Thanks. Yes, I have made a pull request because I think that it already looks better.
Regarding the "dot", I don't know yet. I want to "play a bit", with it so we can explore different options. Do you know how can I do it? I can't find it in this list:

https://gama-platform.github.io/wiki/Statements#chart

**Comment by agrignard** [comment]
I am not a super expert in styling the chart but maybe you can try a bit with:
 style, x_tick_line_visible

And also there the type (we can explore together) type (an identifier), takes values in: {xy, scatter, histogram, series, pie, radar, heatmap, box_whisker}

**Comment by agrignard** [comment]
@LAAP I think you did a good job (and maybe the max we can do with GAMA to improve the design of the chart) what about closing this issue for now?

**Comment by LAAP** [comment]
@agrignard , 

I have tried style, x_tick_line_visible and it doesn't work:

![Captura de pantalla 2020-06-09 a las 12 05 11](https://user-images.githubusercontent.com/19315213/84172068-8f326300-aa49-11ea-82a9-e3d29e21779f.png)

![Captura de pantalla 2020-06-09 a las 12 05 35](https://user-images.githubusercontent.com/19315213/84172126-a2ddc980-aa49-11ea-9205-603aa5a7ad30.png)



So, yes, ok, let's close it. But we have to talk to the Gama team in the future, so the "dots" can be changed in a easy way
