### ISSUE TITLE
Improve mortality rate value

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#116]
@agrignard ,

I am running the model and there are not death agents anymore

**Comment by agrignard** [comment]
see #99

**Comment by agrignard** [comment]
right now the "killing" process is made every day and it takes time to reach a day. I will do it every hour or so

``````
	reflex updateDeath when:every(#day){
		ask (ViralPeople where (each.is_infected)){
			if flip(mortality_rate){
				nb_death<-nb_death+1;
				ask target{do die;}
				do die;
				
			}
		}
	}
``````

**Comment by agrignard** [comment]
Death is back, however, we need to find the right parameter
two parameters to play with 

1. When do we want to apply the updateDeath reflex right now every minute and the mortality rate. 
2. What is the chance I have to die every minute if I have the covid now is 0.1 (maybe to high)

**Comment by LAAP** [comment]
I think that if we can play with the "simulation step speed", and then "mortality rate" in the sliders, then the behaviour will emerge
