### ISSUE TITLE
Clock

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#117]
Hi @agrignard ,

I think that showing a clock with the time/days can be very useful

**Comment by agrignard** [comment]
The clock is here, the problem now is that it takes a long time to have a day done as the step of the simualtion is #1sec (to have a realistic motion) so that's one of the reason the epidemi and even more the recovered guy take so long to appear...

**Comment by LAAP** [comment]
Awesome! It is working!
Yes, that is the reason why we need to "fix" the "Simulation step" So doesn't "get in balance, and keeps spinning"
