### ISSUE TITLE
Triggering the pandemic

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#118]
Hi @agrignard ,
I think that it could be cool to run the model, without pandemic, and then, the user could Triggering the pandemic, so we can see the after and before... What do you think?

**Comment by agrignard** [comment]
How do you see that? As a parameter on the left? trigger epidemy? 

Right now the trigger is simply a throwing a random infected agent, we coudl have somethign a bit more specific to explore different plausible scenarios

**Comment by LAAP** [comment]
I can imagine different options:

1) A tag combined with a number of "started infected people" (so you can explore 1 outbreak with a patient "0" or multiple outbreaks, like "travellers" bringing the disease from outside, for instance). Then, you trigger it, when you are ready to see the outbreak, and randomly (or startin in a district chosen by the user) gets the "victims"

2) You can pic the "victims" with the mouse, clicking into the agent, or you can make infectious surfaces "or buildings" 

3) A combination of above

**Comment by agrignard** [comment]
the point 2 that could be super cool; doable but needs a bit of work

**Comment by LAAP** [comment]
Awesome!!!

**Comment by agrignard** [comment]
First step (not the best one but at least you can start and stop the sim):

press ````i ````will intiate the epidemy
press ````o````will stop it

Right now it's not possible to have a tooggle button directly in the interfadce due to this isuse https://github.com/gama-platform/gama/issues/2986

However we can imagine to have directly on the simulation screen (like a big red button and a big stop) what do you think?

**Comment by LAAP** [comment]
I like the idea of a "big red button"  ;)

**Comment by LAAP** [comment]
Hi @agrignard, 

These are the results of the simulation that I made at high speed, so we can have quick results. The characteristic of the pandemic are: 

- -A "very bad pandemic" that in 11h spreads a lot (infection ratio 0.75
- -Because the speed, the city has not time to put measures of physical distance or masks
- -Asymptomatic ratio is 0.20
- -Mortality is 0.01 (not sure if that is super high, but people are dying in a couple of hours, so I imagine that is super high
- -Initial infection: I only infect 1 person (001)
- -Contamination distance 0024.0 (What is this equal to? 2,4meters?)

So, with that, just having autonomous districts vs conventional, we can see huge differences: 

**Conventional:**

![Captura de pantalla 2020-06-03 a las 10 28 45 (2)](https://user-images.githubusercontent.com/19315213/83890462-ce934380-a719-11ea-9607-ad902750ec31.png)

**Autonomous:**

![Captura de pantalla 2020-06-05 a las 10 46 10](https://user-images.githubusercontent.com/19315213/83890506-de128c80-a719-11ea-98f8-bb5fe9f17992.png)

So, I think that triggering the pandemic with using "i", it is OK.

I will close this issue
