### ISSUE TITLE
Overlapping numbers

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#119]
@agrignard ,

We have a graphic issue, some numbers overlaps (see "walk" and "I"):

![Captura de pantalla 2020-05-13 a las 16 48 48](https://user-images.githubusercontent.com/19315213/81863821-c80a1580-9539-11ea-9a12-66a0e4294060.png)

**Comment by agrignard** [comment]
Yes I see that also sometime... this the randomness of Gama not being great in rendering text

**Comment by agrignard** [comment]
THis will unfortunatelly won't be fixed as it's a gama issue. I close this issue for now
