### ISSUE TITLE
MIT and Andorra District

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#120]
@LAAP what about drawing roughly the kind of district you want on this specific map? Then I can Agentify it later
<img width="1046" alt="Screenshot 2020-05-13 at 22 52 47" src="https://user-images.githubusercontent.com/3928502/81864195-96f70880-956c-11ea-8374-6a6c30f6b19b.png">

**Comment by agrignard** [comment]
Quick one
<img width="1564" alt="Screenshot 2020-05-13 at 23 01 22" src="https://user-images.githubusercontent.com/3928502/81865030-b2164800-956d-11ea-8735-bc5d0bfa66d2.png">

**Comment by LAAP** [comment]
Niiceee!!! Good job! Boston is here!

2 Things:

1) In a realistic setting, I think that we should try to cover most of the space with "bubbles-districts", so no "man land" will not exist even if there are overlaps between the bubbles-districts

2) We need to mark some how the T stations so the flow is bigger between this bubbles

**Comment by agrignard** [comment]
It could help if you can draw them as you are thinking.

One good way is simply to edit this file https://github.com/CityScope/CS_Simulation_GAMA/blob/master/CS_CityScope_GAMA/includes/AutonomousCities/MIT/Districts.shp using QGIS

Then you have to 

1. Create the shape
2. Specify the type fo the district , where you need to put a value in the ````type````attribute and chosse between ```` "R", "S" or "0"````

**Comment by LAAP** [comment]
Hi @agrignard , 

Not sure the reason why but this Shapefile seams not to work in my QGIS. CAn you upload it again?

**Comment by agrignard** [comment]
IS the shapefile working for you? I have no problem on mine

**Comment by LAAP** [comment]
Hi @agrignard ,

It says "not valid data source":
<img width="1440" alt="Captura de pantalla 2020-05-18 a las 12 56 31" src="https://user-images.githubusercontent.com/19315213/82239694-2a329400-9907-11ea-92ea-0cb0eb119c96.png">

**Comment by agrignard** [comment]
I think it comes for your personal configuration 

- Can you try one thing open it from the Guthub folder, what you show me here is from yoru download folder (which ligth not be a folder you can open with QGIS)
-Do you have the other Districts. file (.prj, etc?)

**Comment by agrignard** [comment]
Andorra is in the place now, same thing the Districts are now arbitrary placed it can be more relevant

**Comment by LAAP** [comment]
@agrignard , We should work this together to have something that matches with Andorra a bit more

**Comment by agrignard** [comment]
I will close this issue and we'll reopen a new one. But as it is it is working, then we can focus with the Andorran to have something more realistic but I don't consider it as a bug for now
