### ISSUE TITLE
Add new city: SanSebastian

### ISSUE THREAD

**Issue by imartinezl** [CityScope/CS_Simulation_GAMA#122]
Hi @agrignard !

I am having some issues with the GIS data for the city of San Sebastian. After creating a bound rectangle on QGIS, I have used the [GridDesign.gaml](https://github.com/CityScope/CS_Simulation_GAMA/blob/master/CS_CityScope_GAMA/models/VisualizationToolKit/GridDesign.gaml) file to generate the bounds and the legend. This is the result:

![Screenshot from 2020-05-19 10-35-35](https://user-images.githubusercontent.com/20516006/82304620-da160900-99bc-11ea-9b68-1971a2892636.png)

I have make sure that the CRS is EPSG:4326, but it keeps rotating the bound and the legend. I do not know if this is the expected result. In any case, when I include the GIS data on GAMA, I obtain a skewed version of the districts and the background as well. 

![Screenshot from 2020-05-19 10-16-30](https://user-images.githubusercontent.com/20516006/82303679-94a50c00-99bb-11ea-898f-59ccf80ea0b9.png)

**Comment by agrignard** [comment]
Hi @imartinezl this is coming form the fact that the bounds that you provide for San Sebastian is not rectangle from the beginning. 

Oen of the trick I use in QGIs is to add an OpenStreetMap layer and it should put your "world in the right projection" so your bound is a rectangle and then you can load it in GridDesign

**Comment by LAAP** [comment]
Hi @imartinezl, Happy to have you onboard again!!!

@agrignard , I think that you are trying to mix two models that shouldn't be mixed because they have different scales:

-With the district-bubble model we try to understand how the Autonomy affects to resiliency-Pandemic in terms of mobility and efficiency. And to see how general government policies can impact in the pandemic

-With the more fine grain model we should have "real" agent-buildings from QGIS. The goal of this model is to understand small human behaviour movements and maybe movement inside of buildings and how individual safety measures can help to reopen the economy

So I think that part of the code from the simulations can be shared, but not merge the models

**Comment by imartinezl** [comment]
Hi @agrignard,

Problem solved! There was a misunderstanding between the projection systems of some layers. I just did everything from the beginning and now it works perfectly. 
![Screenshot from 2020-05-19 17-41-00](https://user-images.githubusercontent.com/20516006/82347606-2599d880-99f8-11ea-923d-3f32b1adc6ac.png)

@LAAP happy to learn from you guys and contribute something to the project. 

Regarding your comment, yes, I agree that there are two scales (macro and micro). If I understood correctly, the approach you are proposing is to have two different models working at the same time, right? Is that something feasible to do in GAMA, taking into account that it maybe hard to visualize both scales at the same time?

**Comment by agrignard** [comment]
Good job @imartinezl !! Do you want to make a PR to include this new City?

For the 2 scales model so far it's two differnent model , ultimatley it woudl be great to couple them together

As discussed together there is this repo related to District/City Scale and this one https://github.com/CityScope/CS_Proxymix  for Building scale (closer to what you did in your university) which is related to this issue https://github.com/CityScope/CS_Proxymix/issues/30

**Comment by LAAP** [comment]
Hi gents,

I think that we have 2 models (as minimum), running separately today: The Building level (proximix and @imartinezl 's = Simulation at individuals/person level) and at the city (with several abstracts Districts) level (bubbles = Simulation at metabolic city level). 

What I suggest is to have one in between that is a District level (like a traditional cityscope table), where we combine the knowledge of the two models that we already have (building and city) into a model that answers how the district response internally to the challenge (The sprawl of the pandemic impacting in a district level, but also the reopening amenities, small business vs big business, public transportation, etc. can be questions for the model) . I don't know how to do it, We don't need to have the 3 running in parallel, if that is too much, we can just extract the knowledge to make a 3rd model. This model can use GIS data, and the Agents can behave as an example of people going from home to work (Bubble+cityscope_volpe), stays at work (proximix+cityscope_volpe), goes shopping (bubble+cityscope_volpe). etc.

In the top of this, we should listen to Marc (Andorra) and see what is Andorra's research question for the simulation

Please, let me know your thoughts

**Comment by agrignard** [comment]
Good job @imartinezl San sebastian is now running. is there a reason why the "center" of the city is not really centered? Are you planning to add more districts on the right? If not maybe we can center a bit more the map (it's purely for esthetism and clarity)

**Comment by imartinezl** [comment]
Yes, I was planning to add more districts on the right. The layout of the city is very much conditioned by the orography, and that is why the city expands to the right. 

But I agree that maybe it is better to center it and reduce the scale a bit.
What do you think about this one @agrignard ? =>
![Screenshot from 2020-05-22 12-20-05](https://user-images.githubusercontent.com/20516006/82658145-cc63bc00-9c26-11ea-8cf4-2ec46a7a79cd.png)

**Comment by agrignard** [comment]
Yes looks better, what I was trying to do but it can be perfectible is to have the district embedded inside the legend. Keeping the legend free from Agent. Again this can be discussed depending on the use case

**Comment by LAAP** [comment]
Hi Guys,

**Conventional world:** I think that districts can overlap a bit. In reality the districts will be intersected and different radius. Something similar to:

![Intersected-circles-and-divisions](https://user-images.githubusercontent.com/19315213/82675668-2490c300-9c13-11ea-9e0f-93d7516d7caa.png)

So we can cover all the districts of the city and some overlaps maybe can be showed. At least in the "conventional world"

**Autonomous world:** I think that it can be tagencional circles (autonomous and well organized cities). Maybe the green circle is where we have shared amenities, like hospitals, schools etc.:

![Three tangential circles with inner circle](https://user-images.githubusercontent.com/19315213/82675937-8e10d180-9c13-11ea-9904-660daee3e8a5.png)

**Comment by agrignard** [comment]
I like this drawing and it makes sense actually,

However  it will kill a bit my golden number design  ;-)

<img width="1191" alt="Screenshot 2020-05-25 at 17 06 11" src="https://user-images.githubusercontent.com/3928502/82824694-0f819180-9eaa-11ea-982d-8b71ce5d771e.png">
 
More seriously how can we have both?
For the Autonomous it's doable if the circle touch each other. Then for the conventional world can we think about a layout that look a bit more "elegant" but with the overlap? 

Also the only issue in term of code is that the disctrict are actually the same in both scenarios , what change is just there usage (homogenous vs heteregeneous)

**Comment by agrignard** [comment]
I close this issue related to San Sebastian see #126 for the layout discussion

**Comment by LAAP** [comment]
Hi @agrignard ,

Yes, I think that we should Keep the 2 of them:

1) Abstract city (3 bubbles = Autonomy and conventional) 

2) Realistic (With maps of Andorra, Kendall, etc.... ) The overlapping bubbles

**Comment by agrignard** [comment]
I close this issue as San Sebastian has been added and a dedicated issue has been created for the layout
