### ISSUE TITLE
"Legend.shp" vs "legend.shp" in AbstractCity and Boston folders

### ISSUE THREAD

**Issue by imartinezl** [CityScope/CS_Simulation_GAMA#123]
Hi @agrignard 

Easy issue here: the **Legend.shp** files on the [AbstractCity](https://github.com/CityScope/CS_Simulation_GAMA/tree/master/CS_CityScope_GAMA/includes/AutonomousCities/AbstractCity) and [Boston](https://github.com/CityScope/CS_Simulation_GAMA/tree/master/CS_CityScope_GAMA/includes/AutonomousCities/Boston) folders has the first capital letter, while the rest of the cities have the name **legend.shp**.

I do not know if you are getting any error related to this issue, but in my case GAMA prompted an error (not able to find the location of the legend shapefile). I already renamed the files and the problem vanished. I could do a PR if you want.

**Comment by agrignard** [comment]
they are all with a small l in my case , in the code but also in the folders

Can you share a screenshot of the error you have?

**Comment by imartinezl** [comment]
Here are a couple of screenshots. The model imports the legend.shp (lower case), but on the file tree you can see that AbstractCity has a uppercase L.
![Screenshot from 2020-05-22 11-47-42](https://user-images.githubusercontent.com/20516006/82655295-42b1ef80-9c22-11ea-9d7d-f7872cd7383b.png)

If I run the experiment, I get the above mentioned issue:
![Screenshot from 2020-05-22 11-48-47](https://user-images.githubusercontent.com/20516006/82655299-43e31c80-9c22-11ea-91fc-e0159fbb3c5c.png)

Could this be related to a MacOS vs Ubuntu file issue?

**Comment by agrignard** [comment]
interesting they are all with a l in my case 
<img width="417" alt="Screenshot 2020-05-22 at 11 59 42" src="https://user-images.githubusercontent.com/3928502/82656290-c9b39780-9c23-11ea-9de6-c947bdd8d5fb.png">

YEs it sounds like Ubuntu vs MAc way to handle capital (I know Mac is agnostic to the capital if I remember well)

Are you ok to change it on yoru side to be sure it works on Ubuntu?

**Comment by imartinezl** [comment]
Yes, It works perfectly if I rename the files. 
Since this is not a big issue, I can just rename the files on my side and make sure I do not commit any of this.

**Comment by agrignard** [comment]
No commit it, it's important to have it also working on every computer the same way.

**Comment by agrignard** [comment]
Thanks @imartinezl 

Closed with this commit https://github.com/CityScope/CS_Simulation_GAMA/commit/b5864ee8b9433f1d46a3fe12933b232b7da4eb01
