### ISSUE TITLE
CHART DOESN'T WORK ANYMORE

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#125]
In ````CS_CityScope_GAMA/models/Covid/Autonomous_Covid_Community.gaml````

I don't know what happens but the Health Status chart Doesn't display the right value anymore...

I'll investigate

**Comment by agrignard** [comment]
Very very weird... it work with the last GAMA but not with 1.8 (but it used to work...)

It looks like the update doesn't do its job

`````
int nb_susceptible  <- 0 update: length(ViralPeople where (each.is_susceptible));
`````

**Comment by ptaillandier** [comment]
Need some tests :)

**Comment by agrignard** [comment]
Thank you @ptaillandier , @LAAP will test it in #115
