### ISSUE TITLE
CSV file needs more information

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#128]
@agrignard ,

I am trying to explore to have some results from the model, so we can compare the 2 models (Autonomy vs Conventional). A question, in what units is now measure: time and nbs? 

For that, I will need to get more info from the CSV file. Now we have:

<img width="543" alt="Captura de pantalla 2020-06-03 a las 9 26 09" src="https://user-images.githubusercontent.com/19315213/83642431-d4075700-a57c-11ea-92db-371a110f2e06.png">

Can we add?:

1. Time: in days and hours not in circles
2. Total number of agents in the model
3. Total number of buildings (Shops, office, housing)
4. Number of people walking per "cicle-hour"
5. Number of people commuting per "cicle-hour"
6. Pandemic level per "cicle-hour"
7. City Efficiency per "cicle-hour"
8. Safety level per "cicle-hour"
9. Number of infected, death, and recovered people per profile (P)

**Comment by agrignard** [comment]
Yes I will add it step by step

**Comment by agrignard** [comment]
The first 5 bullet point are made.

**Comment by agrignard** [comment]
OK so the information is nowhere however the number should be more accurate for SafetyLevel, City Efficiency and Pandemic level. I will create a dedicated issue related to this.

@LAAP Please test this new version and tell me if it's ok

**Comment by LAAP** [comment]
Hi @agrignard ,

I think that the KPI indicators are ok. However, not sure if the CSV file is getting all the data. I miss some rows... the most important data from "SafetyLevel, City Efficiency and Pandemic level" are also missing:

<img width="1411" alt="Captura de pantalla 2020-06-05 a las 13 47 55" src="https://user-images.githubusercontent.com/19315213/83907510-86811a80-a733-11ea-9e8f-3ed512a46d6b.png">

**Comment by agrignard** [comment]
OK i understand the proble here, the data are stored but your excel is not loading it correctly, if you look at you're header it's very weird, I think you should specify the delimiter (which is a coma in this case ````,````)

**Comment by LAAP** [comment]
@agrignard , Awesome! You are right!

<img width="1139" alt="Captura de pantalla 2020-06-09 a las 11 50 30" src="https://user-images.githubusercontent.com/19315213/84170301-88a2ec00-aa47-11ea-8dc0-b9cf357c8e7f.png">

It is working now, I am clossing the issue
