### ISSUE TITLE
CSV file not gathering data at all

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#129]
@agrignard ,

The CSV file doesn't gather data any more... After 6 experiments, in all of them, this is the file that I got:

<img width="350" alt="Captura de pantalla 2020-06-03 a las 10 39 11" src="https://user-images.githubusercontent.com/19315213/83650666-990a2100-a586-11ea-9794-958cd7fd174f.png">

**Comment by agrignard** [comment]
Can you retest it, and don't forget to put ```` savetocsv```` to true
