### ISSUE TITLE
KPIS Improvement

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#130]
The 3 current KPIS extract from this model (and exported in a csv file) and are  currently what they are but are maybe too simple? @LAAP what do you think? 

- PANDEMIC_LEVEL:  ratio of  people infected over the total number of people
`````PANDEMIC_LEVEL<-nb_infected/100;`````

- CITY_EFFICIENCY: Ratio of people walking over the total number of people
`````CITY_EFFICIENCY<-	int((nbWalk))/nbPeople;`````

- SAFETY_LEVEL: Ratio of( number people in Quarantine plus wearing mask) over 2times the number of people (to have a value between 0 and 1)
`````SAFETY_LEVEL<-((nbMask+nbQ)/200);`````

**Comment by LAAP** [comment]
@agrignard ,
I think this are ok for this step. We can go more complex in the future if it is needed
I close this issue

**Comment by LAAP** [comment]
Hi @agrignard ,

I reopen this issue. Yes, there are some small changes that we need to make at the KPIs:

----
**You have:**
PANDEMIC_LEVEL: ratio of people infected over the total number of people

`````PANDEMIC_LEVEL<-nb_infected/100;`````

----
**I propouse:** ratio of people infected over the total number of people **THAT STILL ALIVE** (existing population alive in each cicle), so the level of pandemic doesn't decrease if people passes away.

`````PANDEMIC_LEVEL<-nb_infected/(nb_infected + nb_healthy);`````

----
**You have:**
CITY_EFFICIENCY: Ratio of people walking over the total number of people


`````CITY_EFFICIENCY<- int((nbWalk))/nbPeople;`````

----
**I propouse:** Ratio of people **SHOPPING AND WORKING** over the total number of people

`````CITY_EFFICIENCY<- int((nbShopping+nbWorking))/nbPeople;`````

**Comment by agrignard** [comment]
Ok you're right (just don't forget also to reopen the issue (using reopen adn comment instead of just comment)

So here are the change for PANDEMIC LEVEL
``````
PANDEMIC_LEVEL<-nb_infected/length(ViralPeople);
``````

For CityEfficiency the problem is that right now people are only commuting but i can knwo what kind of commute they are doing.

**Comment by LAAP** [comment]
Hi @agrignard,

I Think Pandemic level is working

Regarding 

CITY_EFFICIENCY

I think that it doesn't work. The efficiency needs to be measure against the "full potential of the city", so I think that it should be measuring where people are going, vs inicial population 

````
CITY_EFFICIENCY<-	(length(people where (each.currentTransitStatus="shopping")) / (length(INITIAL-people where (each.currentTransitStatus="shopping"))
````

**Comment by LAAP** [comment]
@agrignard ,
What I mean, is that, since you have death agents, the population shrinks, and the efficiency grows... when the truth is that less people can do less work, and the efficiency should drop

**Comment by agrignard** [comment]
When I do 
`````
CITY_EFFICIENCY<-	(length(people where (each.currentTransitStatus="shopping"))+ length(people where (each.currentTransitStatus="business")))/length(ViralPeople);
`````
The people dying are taken is account here as they are not here anymore (d'est die is the simualtion).

**Comment by LAAP** [comment]
@agrignard , Ok, so something is not working because the indicator gets better during the pandemic wave, even if no people are alive
