### ISSUE TITLE
Documenting the ABMachine Learning

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#131]
0. Modify your ABM model
1. Run it in batch and store the output
2. give the output as an input of the python script
3. Run CityScopable

**Comment by MireiaY** [comment]
I sent you the link to a draft document through Slack. Let me know how much more proper you want it to be, or if you are looking for more or less detail

**Comment by agrignard** [comment]
Is it documented in the github?

**Comment by MireiaY** [comment]
noup... so 5 months later am I still assigned the task? ahahahahah hope to do it at some point within the following 5 months max . I'll let you know ;-)

**Comment by agrignard** [comment]
Do you have any document to link, even if it's not written on github it can be a good starting point for @jmbilbao

**Comment by MireiaY** [comment]
Not any updated one. The following one could be a baseline though:  https://docs.google.com/document/d/1ELYYLDx5CkMZSSaI4Xn7Fkzba8GwEc-nz1nCJowSMLY/edit?usp=sharing

**Comment by agrignard** [comment]
@mireiayurrita any chance to migrate a part of your doc in a wiki page of this repo so we can safely close this issue?

**Comment by mireiayurrita** [comment]
Sure. Give me a couple of weeks, though, so that I get the time for it. Thanks for reminding me this, I had completely forgotten it, and it has nearly been 5 months ;-)

**Comment by mireiayurrita** [comment]
Hello again @agrignard ! I just finished documenting the Dynamic_Urban_Planning repo. Feel free to change anything if you consider it necessary (I have noticed that in some other repos you only include the installation of GAMA in the README section and you put the rest in the wiki section). If you think this works better let me know.

Ah! And could you change the "About" section of the repo from "A joint choice blablabla" to "Dynamic Urban Planning: An Agent-Based Model Coupling Mobility Mode and Housing Choice." ??

Thanksssssss

**Comment by agrignard** [comment]
@mireiayurrita can you point me to the right link so to see the doc? I don't find it in the wiki

**Comment by agrignard** [comment]
Ok great I see it here. https://github.com/CityScope/CS_Dynamic_Urban_Planning Good job it's really well documented. I don't know if this repo will be really active but it would be great to have some people (maybe you? ) keeping the effort. In any case for now this is perfect as it is. We'll see in the following months how this repo evolves.

So I close this (pretty old ;-) ) issue
