### ISSUE TITLE
Provide a complete Hello World example of a cityIO coupling module

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#135]

**Comment by agrignard** [comment]
Loading ok but flipped
<img width="789" alt="Screenshot 2020-10-30 at 22 11 51" src="https://user-images.githubusercontent.com/3928502/97757449-05208f00-1afd-11eb-92ac-f8816e32906e.png">

**Comment by crisjf** [comment]
Hi Arnaud, could you let me know once this is done, I'd love to get my hands dirty with this :)

**Comment by agrignard** [comment]
Hey @crisjf , happy to have you on board for having our hand dirty ;-)

You can start to have a look at the current master where right now GAMA can:

1. Read/load  a grid (dungeonmaster)
`````
string city_io_table<-'dungeonmaster';
file geogrid <- geojson_file("https://cityio.media.mit.edu/api/table/"+city_io_table+"/GEOGRID","EPSG:4326");	
`````
2. Instantiate a series of block from this grid 
````
init {
  create block from:geogrid with:[type::read("land_use")];
  do udpateGrid;
}
````

3. Compute indicator
`````
string computeIndicator (string viz_type){
  string indicator <- "{name: Gama Indicator,value:" + length(block)+",viz_type:"+viz_type+"}";
  return indicator;
}
`````
4. Post indicator (WIP)
````
action sendIndicator(string indicator){

}
````
What I need to see with you now is the format of the string that needs to be send POST to cityIO

So I think the helloworld is getting there then let's have a meeting together today or tomorrow to see how to push this forward

**Comment by crisjf** [comment]
@RELNO what is the endpoint to post simulation results?

**Comment by agrignard** [comment]
I think we will first stay on the **ABM** endpoint but it might evolve if there are different ABM results to post

**Comment by agrignard** [comment]
After a talk with @crisjf the workflow seems pretty straightforward now (it just need to be implemented ;-) and I have crated more atomic issue for see see #137 , #138 and #139 so I close this one
