### ISSUE TITLE
Merge housing choice to master branch

### ISSUE THREAD

**Issue by MireiaY** [CityScope/CS_Simulation_GAMA#136]
So, as I told you the other day the housingChoice branch is divided into two folders. The one called CS_Simulation_GAMA is the one I started to use but because of some heavy commits that were not pushed here we decided to create the second one, CS_Simulation_GAMA_Housing_Choice, which is the one I used until the end of my stay.
![1](https://user-images.githubusercontent.com/58276088/97776661-4307cc80-1b6a-11eb-8ae5-afd75b5b020a.png)

When merging I don't know if the change in name affects but well, just ignore the first folder. When you get into the CS_Simulation_GAMA_Housing_Choice folder, there are the typical 4 folders but don't ask why but I changed the name of the includes folder to includesCalibration, once again I don't know if this affects the merging process. So, the includesCalibration folder at is equally divided into two: City and Criteria. City is equally divided into two: volpe (shapefiles)  and censusDataGreaterBoston. The Criteria folder has real mobility information for Kendall (should this be here? maybe I should put it into the City folder...) and the typical .csv files for mobility characteristics that agents use when making a decision.

BUT if you go into the incentivizedCriteria folder you can see the following:

![2](https://user-images.githubusercontent.com/58276088/97776780-6da65500-1b6b-11eb-825d-ce625b3d2b04.png)

So CriteriaFileCalibrated.csv CriteriaHomeCalibrated.csv are the files with agents-decision making parameter weights are collected, after the error minimization process has been held. If you remember our last meetings in June and July we wanted to open the door to having some behavioural incentives, so an placeholder example of incentivizing diversity acceptance and how this would affect to home criteria and mobility criteria is given in CriteriaFileDiversity.csv and CriteriaHomeDiversity.csv.

When it comes to models. Here we have the 3 models I wrote about in the mail. The CalibrationDataPercentage.gaml is the one used to minimize the error btw simulation and data so that the behavioural patterns (weights given to different criteria) are inferred.  The CalibrationModel.gaml (maybe I should change the name to main model?) is the main general model to obtain the housing and mobility results when financial incentives are given to our agents, so that they move to Kendall. And the CityScopableHousingChoice.gaml is the real-time model.  In the following screenshot you can see that there are two groups of csv files. The first one would be the finer granulated group of files that were obtained when using the KNeighbourRegressor of 4 and the second group would be the results (if I am not mistaken with 100 different cases) that were obtained directly from the GAMA batch experiments.

![3](https://user-images.githubusercontent.com/58276088/97776929-a4309f80-1b6c-11eb-80f9-c0e31815332f.png)

So, the second group is commented because I did not upload these "raw results" to github. BUT, if the first group is used we have to talk about the results folder (which are the results of the predictingValues.py script, which indeed is fed by the results from calibrationModel.gaml batch experiments. But for CityScopableHousingChoice.gaml this would be the equivalent to the includes folder). Anyway, the results folder:

![4](https://user-images.githubusercontent.com/58276088/97777002-39339880-1b6d-11eb-82a9-499ab54897c1.png)

So here each of the ML results is the consequence of having fed the predictingValues.py scripy with the batch experiment results for each of the incentivized scenario (calibrated case, diversity acceptance incentivized scenario and so forth). So although these are results, they are equally necessary to feed the real-time model. The rest is in .gitignore. You can have a look at these .gitignore files, normally I use the ! operator so they are not crazy.

**Comment by agrignard** [comment]
OK it start to be a liiiitle bit clearer ;-)

I can take care of the merge if you are ok with it (I would prefer you to do it so you can keep the "paternity" of this model)

but It shouldn't be difficult seriously.

1. In the master branch just create a **HousingChoice** folder in **models** and one **HousingChoice** in **includes** then just change the path in your model from **includeCalibration** to **includes/HousingChoice** and finally make sure your model are working

2. One important thing I already did the merge in local on my machine but I didn't want to push because the ilcudes folder is a bit too big, for instance City/volpe is 68Mb with for instance some .dbf file, do we need to have those file? It would be great if you can keep just the necessary files in this folder to avoid having a big folder. 

keep in mind that if we put HousingChoice in the master branch anyone that will clone the CS_Simualtion_Gama will carry your files even if they don't use it. So this is one of the challenge to have everything is the master. 

How does it sounds? Are you ok to make this push? If you don't feel confortable the only thing I cannot do for you is to clean the includes file, if you don't feel conforatable to do it in the master then  you can clean it in the HousingChoice branch and I'll the merge after (but I will be the commiter of the file, I would prefer that it's you)

**Comment by MireiaY** [comment]
It doesn't sound too complicated, no. What about the results folder? I guess I should include it too so that the CityScopableHousingChoice.gaml is a runnable model. The problem with the .dbf files that are very big is that they cover the whole Greater Boston area. So, if these are omitted, the calibrationModel.gaml and the calibrateDataPercentage.gaml will not run anymore. This one is meant to be a generic model where the user should include their own area of interest shapefiles, so as long as they manipulate the input files to meet their needs it should be fine, but just I inform you that if I omit these heavy files the two models except for the real-time one will give the typical GAMA error (when a file is missing) if someone just clones the repository and tries to run the models with the files available here. Is it still fine? This could be documented in the WIKI maybe and if the housingChoice branch is kept they could access it to get the file, but well.. just so you know.

If that is fine I will do it in the following days.

**Comment by agrignard** [comment]
Mmm ok I see. If we need to have this dbf files then I am wandering if it makes sense to put in the master (I am a bit memory space freak and don't want to ask people to download 100Mb of data).

So we might think to do a dedicated github for that maybe, no? It might be easier at the end.

**Comment by MireiaY** [comment]
I see that BuildingsLatLongBlock is a previous version of Buildings shapefile. I could get rid of the first one (that would save us 10MB taking into account the .shp itself and .dbf) but apart from that I don't think there is not much I can erase. The biggest file is the .dbf of the apartment_march_great file where the geolocalised results of the apartment web scrapping process are gathered. In this case the shapefile consists of geolocalised points which doesn't have thaaaat much weight but all of the attributes are used in GAMA so the 20MB of the .dbf file are necessary I guess.  But I have a doubt: for example the roads for the Greater Boston Area case and the bus stops have no attributes in GAMA. Theoretically, (I am guessing GAMA takes the shape of the geometry itself from the shpefiles, the attributes from the dbf) that would mean that we can get rid of their respective dbf files ?? simplified_roads dbf would mean having 2MB less and the MBTA_BUS_MAss dbf 2.2MB less. Even doing so, I think going for its own github can be a good idea if we don't want anyone who is not precisely working on this having to have these heavy files downloaded.

**Comment by MireiaY** [comment]
Done. I already cleaned everything I could. Let me know when you decide whether I should merge it to master or create another re`po

**Comment by agrignard** [comment]
Ok cool can you tell me what is the final size of the Housing Choice folder?

**Comment by MireiaY** [comment]
A little bit less than 70Mb

**Comment by LAAP** [comment]
Thank you Guys for keeping the track here!

**Comment by agrignard** [comment]
After some long discussion we have choose for now to store this branch in a dedicated reposetory thatn can be find here
https://github.com/CityScope/CS_Dynamic_Urban_Planning

We'll see later if this project can come back here

@MireiaY are you ok with it? This idea will be to push this HousingChoice projet in the new github

**Comment by MireiaY** [comment]
Okay Done

**Comment by agrignard** [comment]
Awesome! Thank you for the effort so the project is now here
https://github.com/CityScope/CS_Dynamic_Urban_Planning

Let's see how this repo behave, ideally @jmbilbao should be able to iterate on it and maybe @wangcan1213
