### ISSUE TITLE
Numeric indicator 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#137]
Provide an exemple to build and send a numerical indicator to cityIO.

This need to be send here https://cityio.media.mit.edu/api/table/dungeonmaster/indicators

And here the format of the indicators
`````
[{"indicator_type":"numeric","name":"Diversity of land use","value":0.9016420530467626,"viz_type":"bar"}]
`````

**Comment by agrignard** [comment]
Seems to work pretty well now for a Hello World indicator sent by GAMA
see
https://cityio.media.mit.edu/api/table/dungeonmaster/indicators

**Comment by crisjf** [comment]
Nice! Did you push this?

**Comment by agrignard** [comment]
Yes just pushed with your modification also

**Comment by crisjf** [comment]
Looks good! Let's try something more agent-based-like to help us think about the _record_ mode for the simulation. Let's do a random walker that moves between the blocks and count the number of times it visits a park?

**Comment by agrignard** [comment]
Yes of course this is just the Hello World. There is no agent yet in the model to keep it simple for now.

**Comment by agrignard** [comment]
Also we need to be able to send several indicator, right now it just send the last, we should have a list of indicator sent

**Comment by crisjf** [comment]
I already started working on this, see #142

**Comment by crisjf** [comment]
4f8ba7c9c1c54ddb20db9be1b90f3bf96a6fd259 makes indicators their own species.

**Comment by crisjf** [comment]
I think we can close this for now. The numeric indicators are working pretty well. We can reopen if we need to develop them more.

**Comment by crisjf** [comment]
Referencing a commit with documentation here:

8ab9ea8e2f369f477516e259edba1f132953777e

**Comment by crisjf** [comment]
I guess we can also build this using the same logic as the other two indicators and using `cityio_agent` as the parent class.

**Comment by crisjf** [comment]
All indicators now use `cityio_agent` as their parent class.
