### ISSUE TITLE
Heatmap indicator

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#138]
Provide an exemple to build and send a heatmap indicator to cityIO.

This need to be send here https://cityio.media.mit.edu/api/table/dungeonmaster/access

And here is an example for corktown
https://cityio.media.mit.edu/api/table/corktown/access

**Comment by agrignard** [comment]
Current structure
````
{"features":[{"geometry":{"coordinates":[-83.11795226751326,42.3447114591701],"type":"Point"},"properties":[0.0,0.0,0.0,0.0,0.0,0.0],"type":"Feature"},{"geometry":{"coordinates":[-83.05434433459634,42.32556895208527],"type":"Point"},"properties":[0.0,0.0,0.0,0.0,0.0,0.0],"type":"Feature"}],"properties":["housing","employment","education","restaurants","groceries","parks"],"type":"FeatureCollection"}
````

**Comment by agrignard** [comment]
Here we are with a first heatmap sent from GAMA! (just the position of 10 agent with 2 random attribute but the concept is here)
https://cityio.media.mit.edu/api/table/dungeonmaster/access

**Comment by RELNO** [comment]
@agrignard good job!

**Comment by LAAP** [comment]
Awesome!!! Pretty cool!!! It is a small step for ABM but a big step for The CityScope Volpe, Hahhaahh!

**Comment by agrignard** [comment]
Good job to everyone and especially @RELNO the front end is really kicking ass now! it's a **HUUUUUUUUUGE** step indeed both for Gama and CityScope! Looks pretty cool and exciting!

**Comment by crisjf** [comment]
The current version of the heatmap indicator species relies on `people`. We need to make it a bit more generic than that

```
species cityio_heatmap_indicator parent: cityio_indicator {
	// The generic heatmap indicator should not reely on people species. 
	list<people> listOfPoint;
	list<people> return_indicator {
		return listOfPoint; // Not sure about this yet, but we might want this return function just to help users organize their code. 
	}
}
```

**Comment by agrignard** [comment]
@crisjf  Is the creation of the cityio_agent a way to solve this issue? I am not sure to understand the meaning of this classe

**Comment by crisjf** [comment]
Yes! I tested it for the ABM indicator, but haven't checked if it works for the heatmap indicator.

**Comment by agrignard** [comment]
One enhancement to do is to be able to send heatmap from whatever species that inherits from ```heatmapper```

**Comment by crisjf** [comment]
All set with this.
