### ISSUE TITLE
ABM Indicator

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#139]
Provide an exemple to build and send an ABM indicator to cityIO.

This need to be send here https://cityio.media.mit.edu/api/table/dungeonmaster/ABM

And here is an example for corktown
https://cityio.media.mit.edu/api/table/corktown/ABM

or @RELNO and @doorleyr should it be following this format?
https://cityio.media.mit.edu/api/table/corktown/ABM2

**Comment by doorleyr** [comment]
https://cityio.media.mit.edu/api/table/corktown/ABM2 is the format we settled on. You don't have to post the same attributes as Corktown (mode and profile). We designed this format so that your "trips" objects can include whichever attributes you want, as long as you have a corresponding entry in the "attr" object. The "attr" object tells the front-end the names and colors of each of the options (which are represented as integers in the trips object). 

So for example, say you want your trip objects to have an attribute "trip_purpose" with 2 possible values. 
```
{
        "attr": {
        "trip_purpose": [{"name": "home", "color": "#4daf4a"}, {"name": "work", "color": "#ffff33"} .....]
            },

        "trips": [
            {
                "trip_purpose": 0,
                "path": [
                    [-83.0723807, 42.34099439999999],
                    [-83.0723504, 42.3409416],
                    [-83.07231759999998, 42.3408842],
                    [-83.07194399999999, 42.3402318],
                    [-83.07191879999998, 42.3401875]
                ],
                "timestamps": [35683, 35692, 35693, 35693, 35703]
            },
            {
                "trip_purpose": 1,
                "path": [
                    [-83.0723807, 42.34099439999999],
                    [-83.0723504, 42.3409416],
                    [-83.07231759999998, 42.3408842],
                    [-83.07194399999999, 42.3402318],
                    [-83.07191879999998, 42.3401875]
                ],
                "timestamps": [35683, 35692, 35693, 35693, 35703]
            }
        ]
}
```

If you want to add additional attributes to each trip, you just need to add an additional entry to the "attr" object.

**Comment by RELNO** [comment]
^ @doorleyr thanks -- we can discuss (as we've already discussed in the past) having more than one ABM / deckGL trips layers for visualizations, so that both modules can work together. 
If there's no interest in this, I'd revert the layer name to ABM (without the '2') to avoid conflicts.

**Comment by LAAP** [comment]
This is great!!!! I think that @RELNO is right, having more than one ABM. But not sure about the potential technical challenges

**Comment by agrignard** [comment]
Prsonally I I like the deckGL foramt but I can converge to ABM2, just le me knwow.

In any case at some point **ABM** won't mean anything is like saying we have a **mathematical**  indicator ;-)

So @RELNO should I repost to  ABM with the ABM2 format? one we see how to iterate from it? Also it will keep the ABM2 compatibility for now?

**Comment by RELNO** [comment]
The FE is currently looking for ABM2 with the format described by @doorleyr. The `ABM` endpoint won't render at this point.

**Comment by agrignard** [comment]
Ok I go for the ABM2 format then

**Comment by agrignard** [comment]
One last thing for a hello world version do I need to specify an attriute? or can I just sent trips with only path and timestamp? This is for documentation purpose

**Comment by agrignard** [comment]
Ok so I am sending this now (the same structure as the one prposed by @doorleyr in this issue)
https://cityio.media.mit.edu/api/table/dungeonmaster/ABM2

but I cannot visualize it. Black screen on the FE, what do I miss?

**Comment by crisjf** [comment]
This was the format that ended up working

```
 "attr": {
        "mode": {"0": {"name": "home", "color": "#4daf4a"}, "1": {"name": "work", "color": "#ffff33"} .....},
        "profile": {"0": {"name": "home", "color": "#4daf4a"}, "1": {"name": "work", "color": "#ffff33"} .....}
            },

        "trips": [
            {
                "mode": 0,
                "profile":0,
                "path": [
                    [-83.0723807, 42.34099439999999],
                    [-83.0723504, 42.3409416],
                    [-83.07231759999998, 42.3408842],
                    [-83.07194399999999, 42.3402318],
                    [-83.07191879999998, 42.3401875]
                ],
                "timestamps": [35683, 35692, 35693, 35693, 35703]
            },
            {
                "mode": 1,
                "profile":0,
                "path": [
                    [-83.0723807, 42.34099439999999],
                    [-83.0723504, 42.3409416],
                    [-83.07231759999998, 42.3408842],
                    [-83.07194399999999, 42.3402318],
                    [-83.07191879999998, 42.3401875]
                ],
                "timestamps": [35683, 35692, 35693, 35693, 35703]
            }
        ]
```

**Comment by agrignard** [comment]
In this crazy day at least we have **make ABM great again!**
<img width="836" alt="Screenshot 2020-11-04 at 21 52 37" src="https://user-images.githubusercontent.com/3928502/98166695-219b3d80-1ee8-11eb-922e-01e7da1d1096.png">

**Comment by LAAP** [comment]
Awesome @agrignard !  ;)

They are "dancing flamenco" because they are happy to "re-born" in the CityScope. Great job!

**Comment by crisjf** [comment]
art

**Comment by agrignard** [comment]
Yes that's cool! Everyone is  twerking in the river celebrating  the election non results!

<img width="852" alt="Screenshot 2020-11-04 at 22 01 17" src="https://user-images.githubusercontent.com/3928502/98167419-578cf180-1ee9-11eb-858a-db617daebc2e.png">

Good job to everyone at least a good news today!!






Good job to all of us at least a good news today!

**Comment by crisjf** [comment]
@agrignard we need some sort of garbage collector that clears the locations of the agents (the `locs` attribute can grow infinitely large). Otherwise, we will definitely crash cityio. Maybe we can make `locs` a `map<time,point>` instead of a list? That way we rewrite the 7am location everytime the simulation moves to a different day?

**Comment by agrignard** [comment]
Yes it can be a good safety measure. Usually I also stop the simulation after "one day" of simulation so it cannot overload cityIO. But why not having also this map it's a good idea (only issue is that when we restart the day you still carry  the big map with the value from the previous day and potentially a discontinuity with the current loc and the "next" one which is the one rom yesterday

**Comment by crisjf** [comment]
I added a `time_of_day` function in `global` that resets whenever the grid updates. We can use this function to control the update behavior. It also sets itself to zero when the day is done and it stops updating the indicators.

I also created the `cityio_agent` so that users can create their agents as a subclass of this. 

I did notice that when the simulation is updating, we cannot make changes to the grid in the front end. @RELNO is this behavior intended? Maybe the front end should pause the refresh of the indicators when you go to edit mode.

**Comment by crisjf** [comment]
To document: GAMABrix now stays idle when the update is done waiting for cityio to update the GRID.

```
		if (time_of_day()=-1){
			write "ENTERING IDLE MODE";
			do pause;
			loop while: (idle_mode) {
				string new_grid_hash_id <- get_grid_hash();
				if ((new_grid_hash_id != grid_hash_id))  {
					idle_mode<-false;
				}
			}
			do resume;
		}	
		write "TIME OF DAY:"+time_of_day();
```

**Comment by crisjf** [comment]
@RELNO I'm not sure if I posted this somewhere already, but we might want to stop the indicator update in the front end when you enter edit mode. The way ABM indicators work in GAMABrix is that it starts posting information right away, even if it has not computed the whole simulation. That avoids huge lags in the front end between grid update and "I see the cool dots moving." The issue we're seeing is that when GAMABrix is posting new updates, the front end is refreshing like crazy and you cannot edit the grid. 

I'm happy to repost this in another repo if needed. Not sure where this issue should live.

**Comment by RELNO** [comment]
@crisjf thanks -- let's pull continue this conv @ the FE repo

**Comment by agrignard** [comment]
I close this one as it might be related to FE, if we need to implement 2 mode in GAMA let's reopen it

**Comment by crisjf** [comment]
Please note that all indicators are now only uploaded twice, once with a preview and then after the whole day as been simulated.
