### ISSUE TITLE
Include Readme and update it in the CityScope doc

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#140]
@crisjf I let you see how to integrate automatically this readme in the CityScope doc
https://github.com/CityScope/CS_Simulation_GAMA/blob/master/CS_CityScope_GAMA/models/cityIO/README.md

**Comment by crisjf** [comment]
[Done](https://github.com/CityScope/cityscope.github.io/blob/new_docsite/docsite/docs/modules/Simulation_GAMA/Simulation_GAMA.md). The `md` file now will update automatically every night, and it should show up in the website the next time Ariel re builds the docs.
