### ISSUE TITLE
Check hash before updating local grid

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Simulation_GAMA#141]
Issue for documentation. 

CityIO maintains a series of hashes to track the table update [here](https://cityio.media.mit.edu/api/table/dungeonmaster/meta/hashes). If the hash does not change, that means the table state has not changed. The model should get the hash and perform the update only when the hash changes.

**Comment by crisjf** [comment]
@agrignard you'll see now that when the model is running, any update to the table in the front end will update your local grid as well. And that this is done by checking for a hash update before getting the new object.

**Comment by agrignard** [comment]
Ok great, I reopen this I might have to find a way to chekc maybe not every iteration, it sounds pretty heavy to check every step. I guess we can have a parameter that ask to check every N iterations

**Comment by crisjf** [comment]
I added a simple `when` to the reflex. I think the use case we're going for is that under deployment (i.e. the model is ready and running), the model stays idle until someone updates the table. Then the model starts to run with the new setting. Does this make sense to you?

**Comment by crisjf** [comment]
Now that I think about it, we might also want a global dummy that signals `record_mode` on or off.

**Comment by agrignard** [comment]
Can we have GAMA updating the grid even if it's the same hash at cycle=0, will be easier to debug (we can put a boolean)

**Comment by crisjf** [comment]
This should be the current behavior because the `grid_hash_id` starts empty, so the first iteration will update.

**Comment by agrignard** [comment]
Ys it was because of the modulo in fact (but I also add a forceUpdate which is maybe useless now). So this issue should be fine

**Comment by agrignard** [comment]
I guess we can close this one, feel free to reopen it if needed
