### ISSUE TITLE
To post multiple numeric indicators we need to post a list

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Simulation_GAMA#142]
The way we are currently posting the numeric indicators uses `save(json_file(string,map<string,unknown>))`. This limits us to always post a map, but to add multiple numeric indicators we need to be able to post a list of maps. See [corktown](https://cityio.media.mit.edu/api/table/corktown/indicators) as an example. 

I tried doing `save(json_file(string,list<map>))` but it did not work well.

**Comment by agrignard** [comment]
We should build the right string instead in ```` string myIndicator;```` and post it

**Comment by crisjf** [comment]
I can work on this. 

What was the reason for saving the results of the indicators as an intermediate step?

**Comment by crisjf** [comment]
How do I post a string? I'm guessing `save(json_file(string,map<string,unknown>))` won't work anymore

**Comment by agrignard** [comment]
What I am trying to say is that the string itself should embed the list of string

**Comment by agrignard** [comment]
I think we can consider it as closed no? Regarding what is now posted
`````
[{"indicator_type":"numeric","name":"Mean Height","value":51.34952140692907,"viz_type":"bar"},{"indicator_type":"numeric","name":"Min Height","value":1.377802165684261,"viz_type":"bar"},{"indicator_type":"numeric","name":"Max Height","value":99.6854835751274,"viz_type":"bar"}]
`````

**Comment by crisjf** [comment]
Just to document: The issue is that I was using an older version of GAMA.
