### ISSUE TITLE
Link Gamablock and CityScope Type 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#143]
Right now block are very simple (
`````
species block{
	string type;
	rgb color;
	aspect base {
		  draw shape color:color border:#black;	
	}
}
`````
we'll soon need to embed the CityScope ```type```inside in the same way it gets the color from the geogridata

**Comment by crisjf** [comment]
This will be super important as the user will eventually interact with these blocks, and not with geogrid_data. This is a way in which python brix and GAMA brix will be different.

**Comment by agrignard** [comment]
species ```block``` are now reading the field ```"name"``` in ```GEODRIDATA``` and store it in type.

is that enought for now? I am not dealing at all with the LBCS ratio etc. I guess this is another question. For now we can consider the high level cityScope type

**Comment by agrignard** [comment]
@crisjf  Do we need/want/can get other information? Right now the ```name``` (Residential, Park ,etc) and ```height``` are embedded in the attribute ```type```of the species ```block``` I don't think we can get other

**Comment by crisjf** [comment]
Ideally, each block will be a copy of the blocks in the table. It's actually pretty cool, because it means that GAMABrix won't need a `geogrid_data` as an input to the indicators because it will always keep an updated copy of the grid locally. But for that, we need to make sure each block has all the necessary information.

**Comment by agrignard** [comment]
Ok, di we know what are the necessary information?

**Comment by crisjf** [comment]
This is where we connect with the CS standard.

Every block in `GEOGRIDDATA` linked to a CS-type:
https://cityio.media.mit.edu/api/table/dungeonmaster/GEOGRIDDATA

And the types definition for each table can be found here:
https://cityio.media.mit.edu/api/table/dungeonmaster/GEOGRID/properties/types

So what GAMA should do is:
1) On init, get the types and store them locally.
2) Whenever the action that updates de local grid is run, each block should retrieve their properties from the locally stored type definitions.

Makes sense?

**Comment by agrignard** [comment]
Ok so the CS-type are now updated as soon as the grid change https://github.com/CityScope/CS_Simulation_GAMA/commit/3aaf8cc686961876ecb7cd2875ba73fcc092e2bc

Do we want to go deep in the types definition? I think for now Cs-types are enough, isn't it?

**Comment by crisjf** [comment]
We at least need to store a map with the types definitions from:
https://cityio.media.mit.edu/api/table/dungeonmaster/GEOGRID/properties/types

This should be updated only when the model initializes.

**Comment by agrignard** [comment]
@crisjf not sure exacty if this is what we want but I just pushed an action that stores the type as a map in ```setup_static_type``` is that enough? What do we do then with this map?

see this commit https://github.com/CityScope/CS_Simulation_GAMA/commit/a888eb18a7368601cb8a10a96419f467721d0551

**Comment by agrignard** [comment]
Quick summary of the status of this issue.

The global definition of the type can be found here 
https://cityio.media.mit.edu/api/table/dungeonmaster/GEOGRID/properties/types
and his counter part is stored in the GAMA model here as a global variable 
````
map<string,unknown> static_type;
````
and filled in ```action setup_static_type ``` in ``` GAMABrix.gaml```

and then the idea will be to store in every instance of the species ``` block ```  the property of each block in 
````
map<unknown, unknown> block_type_properties;
````

@ptaillandier 
would it be possible to have some help to fill this map ```block_type_properties```we have some difficulty with the GAML Synatx.

**Comment by agrignard** [comment]
@crisjf seems to be done by @ptaillandier . let us know if this is what you wanted.

**Comment by crisjf** [comment]
Thanks for the push @ptaillandier 

Commit 435999c622040bb7a6496c426c733f4d10494462 takes it a step further and parses `NAICS` and `LBCS` codes from the `static_types`. Every bock now has a `block_naics` and `block_lbcs` maps that the user can directly access.

**Comment by crisjf** [comment]
Note: the parser also transforms this

![image](https://user-images.githubusercontent.com/8973959/99101345-7dca2580-25aa-11eb-8708-feb3e7f93274.png)

into this 
```
LBCS : { 6700: 0.3, 2310: 0.21, 4100: 0.49}
```

**Comment by agrignard** [comment]
Great!!!
