### ISSUE TITLE
Models break when the initial state of the table has cells with no height

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Simulation_GAMA#144]
The line:
`geometry shape <- envelope(geogrid);`
breaks when the geogrid object has no height. In general, the height will not be specified in `GEOGRID`, so we need to make sure the model does not crash if this is the case.

I created a table called `dungeona` to test this. This table has some cells with height and some cells without height. `dungeonmaster` happens to have all cells with height initially.

**Comment by crisjf** [comment]
@RELNO you might also want to take a look at this

**Comment by agrignard** [comment]
How can I reproduce it? How o you produce a grid with no height? I don't understand how it can impact the ```envelope``` function

**Comment by RELNO** [comment]
@crisjf  
> In general, the height will not be specified in GEOGRID

I actually think it does, see https://cityio.media.mit.edu/api/table/dungeonmaster/GEOGRID

**Comment by crisjf** [comment]
@agrignard point the model to the table `dungeona`

@RELNO, see this table:
https://cityio.media.mit.edu/api/table/dungeona/GEOGRID

**Comment by RELNO** [comment]
@crisjf -- I do see `height` attr

**Comment by crisjf** [comment]
Not all of them have height, which breaks the `envelope` function. 

![image](https://user-images.githubusercontent.com/8973959/98143124-b5441e00-1e96-11eb-895a-971be86f80ea.png)

I think this has to do with the table constructor allowing for some types not to declare a height. See the example below, where `Park` does not have a height.

![image](https://user-images.githubusercontent.com/8973959/98143263-df95db80-1e96-11eb-96a4-2d9319f6b3cc.png)

**Comment by crisjf** [comment]
I'm gonna close this for now. The error is still there with `dungeona` but I've tried to reproduce it with three other fresh tables and I've gotten no error so far.
