### ISSUE TITLE
Packaging of GAMABrix

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Simulation_GAMA#146]
I placed the `GAMAbrix` functions in their own file to be imported by a model builder. I'm gonna start working on the documentation for this. 

The only pending thing is to move 
```
file geogrid <- geojson_file("https://cityio.media.mit.edu/api/table/"+city_io_table+"/GEOGRID","EPSG:4326");
geometry shape <- envelope(geogrid);
```
inside `GAMABrix.gaml`. Ideally, the user will just need to define the table name and the setting of the world using the table geometry should be done in `GAMABrix`.

**Comment by crisjf** [comment]
Documentation is here:
8ab9ea8e2f369f477516e259edba1f132953777e

and here:
https://github.com/CityScope/CS_Simulation_GAMA/blob/master/CS_CityScope_GAMA/models/cityIO/README.md

**Comment by agrignard** [comment]
Great  job for the doc @crisjf , I think we can close this issue for now
