### ISSUE TITLE
Comment on the fly about the doc

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#153]
@crisjf great job for the doc! it's great. I have some thought that we can discuss here

At the end shouldn't we call or ```block```species ```brix```? to be coherent? I find it confusing for the user to make the distinction between block and brix
In https://cityscope.media.mit.edu/docs/modules/GAMA/#setup
Do we still need cityio_numeric_indicator ? Now everything is in cityio_agent isn't it?

In https://cityscope.media.mit.edu/docs/modules/GAMA/#basics-of-building-a-cityscope-indicator-in-gama
An indicator will basically take in the properties of the block agents in the world=> an indicator can also be independent of the block no? e.g the mean age of each agent? aybe we should explain from the beginning that the GAMA module can compute indicator from the grid it self like brix at the end but more importantly can generate indicator from a simulation

In https://cityscope.media.mit.edu/docs/modules/GAMA/#gamabrix-for-cs-brix-users
While brix can handle multiple tables at the same time by creating multiple threads for each Handler, GAMA is constrained to one table per model.=> should we work on that?

In https://cityscope.media.mit.edu/docs/modules/GAMA/#building-an-indicator-output
is_heatmap<-false.=> true?

After https://cityscope.media.mit.edu/docs/modules/GAMA/#full-module-example-with-comments
maybe can be nice to have a screenshot of how it look in the FE?

**Comment by crisjf** [comment]
Hi Arnaud,

* Let's call it `brix`, I can change that
* We can use `cityio_numeric_indicator` as a constructor of simple numeric indicators (e.g. average, max, count, etc). `cityio_numeric_indicator` actually inherits from `cityio_agent`. It is not necessary, but it might prove useful so we can leave it. 
* An indicator can depend on any agent, you are correct. I'll make this clear.
* I don't think it makes sense to have multiple tables in the same GAMA model. This would mean having multiple GAMA worlds, and I haven't seen that.
* `is_heatmap<-true`
* I'd keep it simple for now. The model is simple enough that anyone can copy and paste it in their local GAMA UI and try it by themselves.
