### ISSUE TITLE
Wrong instance in Brix (conflict with type)

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#155]
When brix are instantiated when we inspect them they should appear as an instance of brix with a cs_type (e.g Road)

So far they appear as an instance of Road instead of an instance of brix...

Strange behavior...

**Comment by crisjf** [comment]
This is what I see. Where are you looking at the `instance of`?

![image](https://user-images.githubusercontent.com/8973959/99973589-eadd7800-2d6d-11eb-8e94-47fd2900f606.png)
![image](https://user-images.githubusercontent.com/8973959/99973609-f29d1c80-2d6d-11eb-9b1c-e99b17230061.png)

**Comment by agrignard** [comment]
Happening with
https://cityscope.media.mit.edu/CS_cityscopeJS/?cityscope=team-1
but not with
https://cityscope.media.mit.edu/CS_cityscopeJS/?cityscope=dungeonmaster

**Comment by crisjf** [comment]
Not it also happens with `dungeonmaster`

But here's what's going on:
When you
`create brix from:geogrid;`
you're using the initial state of the table defined in `GEOGRID`. Each block in `GEOGRID` has now `properties/name` that was not there before. GAMA is using this `name` to define the block as an instanceof the name. 

![image](https://user-images.githubusercontent.com/8973959/99985691-46aefd80-2d7c-11eb-9e4c-40d56dbb5c4c.png)

This has the issue that when we do `udpateGrid` and `ask brix` to do something, there is no brix agent, so the grid does not update from `GEOGRIDDATA` and instead stays static as it was defined in `GEOGRID`. 

The solution is to make sure that when we do `setup_cityio_world`, we remove the `name` from `geogrid`. @agrignard could you try doing that?

**Comment by agrignard** [comment]
I keep this open so that @ptaillandier can also have  a look as it might impact GAMA also
