### ISSUE TITLE
Post data to GeoGridData

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#161]
This has already been done in Gama in the past so it's just a question of convention weither we want to do it or not (I personally think it makes sense) 
https://github.com/CityScope/CS_CityIO/blob/master/examples/GAMA/cityIO_Gama/models/cityIO.gaml

This is link to this issue also 
https://github.com/CityScope/CS_Brix/issues/19

**Comment by crisjf** [comment]
I think it makes sense to do it. We need to make sure that:

1. The posted object has the right format.
2. The posted object does not refer to a cell type that is not defined in `GEOGRID`.
3. The posted object has the right number of cells. 

This shouldn't be difficult to do in GAMA.

**Comment by agrignard** [comment]
I think this issue can be considered as closed
