### ISSUE TITLE
Cannot send anymore to cityIO

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#163]
Gama used to send information to cityIO before using this syntax for instance
save(json_file("https://cityio.media.mit.edu/api/table/update/"+city_io_table+"/"+type, m));

It seems not to work anymore.

Did something change in the way to post information?

**Comment by crisjf** [comment]
See @yasushisakai comment here:
https://github.com/CityScope/CS_CityIO/issues/128

If I remember correctly, we `save` to post things to cityio, and this function seems to support adding a header
https://gama-platform.github.io/wiki/Statements#save

The `header` parameters is a boolean though, so I'm not sure how to pass it the parameters we need

We need to change the current lines:
```
save(json_file("https://cityio.media.mit.edu/api/table/update/"+city_io_table+"/"+type, m));
```
for something that looks like
```
save(json_file("https://cityio.media.mit.edu/api/table/"+city_io_table+"/"+type+"/", m), header=True, attributes=cityio_header);
```

where `cityio_header` is `Content-Type:application/json`.
