### ISSUE TITLE
Move GAMA-Brix to its own repo

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Simulation_GAMA#165]
Should we move GAMA-Brix to its own repo?

Might be worth it, since users can get lost searching for GAMA-Brix in a large repo that includes multiple other models. 

Eventually, we should turn `GAMA-Brix` into a plugin model.

**Comment by agrignard** [comment]
If this repo is well documented (which is maybe not the case) I think it's ok to keep it here, where we have all the GAMA compatible project.

At the end a Gama Brix model is just one or 2 file so I don't know if it deserves its own repo. 

For the structure of this repo and to make it easier to understand I am open to discussion if we need to reorganize it

What do you think?

**Comment by crisjf** [comment]
I'm still leaning more towards having it in its own repo. It's just more user friendly for someone to see a readme with all the instructions on how to "install" the package. To get it started, we can fork this repo and clear everything that is not Gama brix. That way we keep the history.

Let's ask @RELNO what he thinks as this also relates to the broader organization of the ecosystem.

I saw that GAMA has a especial class of models called "plugin models," how are those setup? Should Gama brix be a plug-in model?

**Comment by crisjf** [comment]
This
https://gama-platform.github.io/wiki/DevelopingPlugins

And this 
https://gama-platform.github.io/wiki/InstallingPlugins

Will be relevant

**Comment by crisjf** [comment]
https://github.com/CityScope/CS_GAMABrix

All set :)
