### ISSUE TITLE
Pie Charts seem to be broken 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#29]
In dev run game_it_v1.0.gaml pie charts doesn't work properly (index ouf of bounds)

It used to work? Something related to GAMA 1.7 vs GAMA 1.8?

**Comment by agrignard** [comment]
@tnguyenh can you check on your version? I am now on GAMA 1.8 and it's kind of difficult to go nack to GAMA 1.7

**Comment by tnguyenh** [comment]
It seems that the function "polygon" does not work as intended. polygon([]) should return the point {0,0}, but instead it throws an exception. It works fine on the last Gama version, it seems that it is related to the compatibility of Gama with your Java version. We'll send an issue for Gama developers.

**Comment by agrignard** [comment]
It has been raised in GAMA here
https://github.com/gama-platform/gama/issues/2326

**Comment by agrignard** [comment]
Thank you @tnguyenh 
It has been fixed with
https://github.com/CityScope/CS_Simulation_GAMA/commit/c10c9a83a9d8a02f8205735471155a2601639e58
