### ISSUE TITLE
documentation: qgis(geofabrik)->export4gama :)

### ISSUE THREAD

**Issue by tuxun** [CityScope/CS_Simulation_GAMA#36]
Please, add a few notes about how to use qgis for make a map for the gama simulation project.
the simulation code look for building of type ("R") at start for put agent in it so they can start to move, shouldnt i use a filter for select them on map and assign them this attribut in qgis? 

ps: and for volpe, from where do you got these csv? :)

**Comment by agrignard** [comment]
QGIS is a software to edit shapefile, this repo is not the place to document on how to use QGIS.

If you want to learn QGIS you can have a look here:
http://www.qgistutorials.com/fr/

**Comment by tuxun** [comment]
strangely, there is no tutorial on what your project want, in the qgis tutorials

**Comment by agrignard** [comment]
If you want to learn GAMA then I suggest to start from here
https://gama-platform.github.io/

However it would be easier with a knowledge in QGIS or ArcGis 

Then if you want to run this model you can follow this link
https://github.com/CityScope/CS_Simulation_GAMA/wiki/Run-CityScope

**Comment by tuxun** [comment]
note: you dont need to give links i already had, just a short explanation like: buildings are polygons rassembled in a .shp, road are lines assembled in a shp, dont forget to add table boundries, this sort of thing
