### ISSUE TITLE
Bike use increase in a linear value

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#39]
At the CSV file we can see that something is wrong with the "Bikes". It is increasing in a linear growth
<img src=https://www.dropbox.com/s/ykc5vckqtgb1sq0/Bike.png?dl=0 />

**Comment by agrignard** [comment]
Which column of the csv file are you plotting? When I look at the csv column of your picture the column bike (C) doesn't look as a linear increase. Don't you think you are plotting the column "cycle" (A)?

**Comment by LAAP** [comment]
Sorry, yes it is the "cycle" (fist column) and last column bus_distance

**Comment by agrignard** [comment]
So we close this one ;-)
