### ISSUE TITLE
bus_distance = 0.0 all the time

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#41]
Other issue is that at the .csv, the "bus_distance" is = 0.0 all the time and in all the simulations

**Comment by agrignard** [comment]
Your right currently the distance traveled is only computed in the reflex ````move```` with this line for walk,bike and car but not in the reflex ````move_bus````.

``````
transport_type_distance[mobility_mode] <- transport_type_distance[mobility_mode] + speed/step;
``````
However for bus it's a bit different and we need to discuss how to we want to compute the distance, 
1. Do we want o know the travel distance per people by bus
2. Do we want to know the distance travel by a bus (independtly og the peopel inside), soem time a bis is travelling while empty, so I think this more make sense. 

Let me know which option, the option 2 would be easy to implement.

**Comment by LAAP** [comment]
We want ti know both 1 and 2
