### ISSUE TITLE
Create model for Aalto campus which extends CityScope_main.gaml

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_Simulation_GAMA#44]
As discussed with @agrignard and @SannaIltanen, we need to create an ABM for the campus with a lot of the same functionality as CityScope_main.gaml. However, some functionality will need to be modified/extended. For example:
- grid data in cityIO 2.1 format needs to be parsed
- the sliders do not exist
- locations of car parks should be modelled
- there should not necessarily be a 1:1 relationship between residential types and office types.

What is the best way to do extend an existing model? Should we import the entire model CityScope_main.gaml? If we do this, can we then overwrite certain parameters and methods of the model?
Or can we import specific parts of CityScope_main.gaml? eg. can we import all the species and experiments but write new code for the global parameters and reflexes?

**Comment by agrignard** [comment]
A first working version is now implemented. Need to be tested also on the Aalto campus but the integration is done here.

We can now split the sub issues in different issues. 

grid data in cityIO 2.1 format needs to be parsed=> Done
the sliders do not exist=> for now it is hardcoded

locations of car parks should be modelled=> @doorleyr can you create a more explicit issue on this I am not sure to understand what you mean?

there should not necessarily be a 1:1 relationship between residential types and office types= => @doorleyr can you create a more explicit issue on this I am not sure to understand what you mean?

**Comment by agrignard** [comment]
Thanks to this 2 commit https://github.com/CityScope/CS_Simulation_GAMA/commit/de2a96f06d9e8775e3448d96e9f8c876be027db9 and https://github.com/CityScope/CS_Simulation_GAMA/commit/4c07b42fd27459b9e5063089154c3a44957e52c0 the import is very straightforward. the aalto extension is now very very light (less than 50 lines) Right now all the information could even be stored in a configuration file, however with this structure, we are free to overwrite some of the methods that are in the cityScopemain.gaml

I close this issue for now as the aalto model is now doing exactly what we wanted. 

For further improvement depending on what needs to be explored on this project let's open dedicated issue
