### ISSUE TITLE
Create charts to show important indicators in real-time

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_Simulation_GAMA#49]
The Aalto model should have some charts (eg. time series plot, histogram, bar chart etc.) to show the most important indicators in real-time. Some examples of important indicators include:
- the total km travelled by cars
- the parking pressure (average/max over time or maybe a dynamic histogram)
- the number of drivers who cannot find parking spaces
- etc.
Some examples of projects using charts can be found in the sample projects or in other CityScope projects. eg:

https://github.com/CityScope/CS_Simulation_GAMA/blob/devEnergy/CS_CityScope_GAMA/models/SandBox/Energy/SolarBlockChain.gaml

https://github.com/CityScope/CS_Simulation_GAMA/blob/master/CS_CityScope_GAMA/models/Game_IT.gaml

**Comment by Babakfifoo** [comment]
Charts of capacity and count of agents which cannot find parking is fixed. Other charts will be fixed soon.
