### ISSUE TITLE
Use data about internal and external flows to improve representativeness of model

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_Simulation_GAMA#50]
Right now all trips take place between buildings on campus and the number of agents is arbitrary. A number of changes should be made to improve the realism of the model.
1. Get some data on 
- the numbers of people arriving to the campus each day and how many of them drive.
- the number of people living and working/studying on campus and how many of them drive
2. Create some external zones representing the main entry/exit points to the campus. Create "commuter" agents who "live" in these zones.
3. Based on the data in point 1, simulate the correct number of internal and external driving trips.
4. The number of agents will probably be too high to simulate so just simulate some fraction of them. Make sure to reduce the capacity of the car parks by the same factor.

Point 1 may take some time but we can proceed with points 2 to 4 with some assumed numbers for now.

**Comment by agrignard** [comment]
@doorleyr Is this issue still relevant?

**Comment by doorleyr** [comment]
Resolved
