### ISSUE TITLE
Impossible to write to cityIO 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#52]
````
save(json_file("https://cityio.media.mit.edu/api/table/update/grasbrook/cityIO_Gama_Hamburg", c));
````

Doesnt work anymore

**Comment by doorleyr** [comment]
@yasushisakai do you have any ideas why this stopped working?

**Comment by yasushisakai** [comment]
when did this stop working?

**Comment by doorleyr** [comment]
I think some time in the last 2 weeks. It was working before @agrignard travelled to France but not working when he came back.

**Comment by agrignard** [comment]
Ok it seems to rework now

**Comment by yasushisakai** [comment]
great to heat that!
