### ISSUE TITLE
Clarify Campus Residential Building Types

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_Simulation_GAMA#53]
Currently all person agents pick their housing from the full list of vacant houses. However, students and staff should have different choice sets and/or preferences. To implement this, we need to know which person types prefer which housing types.

The residential buildings in the Buildings and Campus_Buildings shape files have a Scale attribute with values S, M or L.  @sannailtanen What kinds of housing do each of these categories represent and how were they determined?

We have 2 types of people seeking housing: students and staff? Which of the housing types above are student housing and which are for staff/others?

**Comment by Babakfifoo** [comment]
The housing in the peninsula is owned by AYY and HOAS. They provide student housing. They could be allocated for students. There is a minor issue that Ph.D. students are counted as staff and cannot rent from AYY while they can rent from HOAS.
housing outside of this area is unknown. They are not necessarily work at university.

**Comment by doorleyr** [comment]
So HOAS is for all students and AYY is for all students except PhD, is that correct? We don't differentiate between student types so if that's the case, we should probably just treat all students as non-PhD. The number of PhDs should be small relative to total student body anyway.

The private housing should be accessible to all I guess.

@sannailtanen can you please add a column to the buildings shape file to indicate whether each residential building is student housing or private housing.

**Comment by sannailtanen** [comment]
I added into the 'includes' folder an optional buildings_2 shape file(s) which is more up to date. I updated in the Usage field type 'S' which means housing for only students (and R remains housing for others). I also upadated the Scale field according to floora area of building register (of the municipality). There are now three classes S:0-1500,  M:1501-10000, L:10001- [m2].

I also added floor_area in square meters and number of residents (according to register data) as own fields if we want to use more accurate data.

**Comment by doorleyr** [comment]
Ok thanks this is helpful. However, I notice that the three buildings shapefiles 'Buildings', 'Campus_Buildings' and 'Buildings_2' all have slightly different buildings. See screenshot from QGIS. Are they different for a reason? I know you said that buildings_2 is the most up to date but there are some buildings in the other shape files which are not in buildings_2. Are these buildings that are no longer there or in use? 

<img width="993" alt="Screenshot 2019-09-20 at 13 10 19" src="https://user-images.githubusercontent.com/7722116/65326006-50e9d080-dba8-11e9-96a1-1ba737e8871c.png">

**Comment by agrignard** [comment]
@doorleyr Is this issue still relevant?

**Comment by doorleyr** [comment]
Resolved
