### ISSUE TITLE
Content and Style of labels of pie chart

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_Simulation_GAMA#54]
I've created some dynamic pie charts for the Aalto simulation. However, as shown in the image below, the labels are generated automatically in a way that is hard to read. How can we customise the content of the labels the width of the label boxes (so that the text doesn't get split across multiple lines).

<img width="294" alt="Screenshot 2019-09-11 at 14 52 32" src="https://user-images.githubusercontent.com/7722116/64703438-55293600-d4a4-11e9-99f0-54b18edac368.png">

**Comment by agrignard** [comment]
@doorleyr Is this issue still relevant?

**Comment by doorleyr** [comment]
Yes, I didn't figure it out. Should I just email the question to this address?: gama-platform@googlegroups.com

**Comment by benoitgaudou** [comment]
Hi,
The GAMA model library provides many examples of charts in Visualization and User Interation / Visualization / Charts / model, such as model Pie.gaml.

In your case, does the facet `tick_font` of the statement `chart` do the job?  

```
chart "Nice Ring Pie Chart" type: pie style: ring background: # darkblue color: # lightgreen axes: # yellow 
	title_font: font( 'Serif', 32.0, #italic)
	tick_font: font('Monospaced' , 64, #bold) 
	label_font: font('Arial', 64, #bold) 
	x_label: 'Nice Xlabel' 
	y_label: 'Nice Ylabel' {
   .......
```
