### ISSUE TITLE
Toggle between views

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Simulation_GAMA#58]
Need to toggle between views depending on the flavor of the model. For now, there's a global parameter (modeCar) that should control which view we show. 

Very view should also have a view mode without the buildings to clearly show the location of people.

**Comment by agrignard** [comment]
@crisjf Do you still have this issue? What do you mean by "toggle between views depending on the flavor of the model"

**Comment by crisjf** [comment]
I was trying to use a parameter to control what agents get rendered so that some can be toggled off with a click. I think it was that.

**Comment by agrignard** [comment]
What about using an event with a specific key? or you can also use mouse_event if you prefer to click

**Comment by crisjf** [comment]
Yeah, I think we already solved this one. I got confused. Sorry about that.
