### ISSUE TITLE
MicroFromMacro simulation should use geojson features as home and work locations rather than coordinates

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_Simulation_GAMA#63]
The latest OD data on cityIO has new attributes of "home_sim" and "work_sim" for each person. Eg.
"home_sim": {
"ind": 4,
"type": "portal"
}

"work_sim": {
"ind": 100,
"type": "meta_grid"
}

The 'type' refers to whether this location is a cell on the meta_grid or a portal. The 'ind' refers the index of the grid-cell or the portal.

In the example above, the agent's home location is the 4th feature in the portals geojson. The agent's work_location is the 100th feature in the meta_grid geojson.

The portals geojson can be found here:
https://raw.githubusercontent.com/CityScope/CS_Mobility_Service/master/scripts/cities/'+CITY+'/clean/portals.geojson'

The meta_grid geojson is on cityIO:
https://cityio.media.mit.edu/api/table/'+TABLE_NAME+'/meta_grid

For now, the OD data still has the 'home_ll' and 'work_ll' attributes but once the simulation has been updated, these will no longer be sent to cityIO.

**Comment by agrignard** [comment]
Ok I will integrate this in the ABM

For now there is only this information in Corktown, can you put it also in Grassbrook?

**Comment by agrignard** [comment]
Closing this issue as it s not relevant anymore
