### ISSUE TITLE
ABM endpoint holds invalid data 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_Simulation_GAMA#67]
https://cityio.media.mit.edu/api/table/grasbrook/ABM

**Comment by agrignard** [comment]
This is very weird. I didn't change anything on my side since friday. When I print my file (results.json) I have the value in the path. 

@yasushisakai Anything new in cityIO ?

**Comment by yasushisakai** [comment]
It's the same instance that's running this past 2 months. What is invalid here? I see valid JSON data.

**Comment by agrignard** [comment]
tje json is valid, but for a unknown reason there is no value in path and timestamps. I'll dig it

**Comment by agrignard** [comment]
back, however I don't understand why it was not valid. Maybe because the simualtion was running for several days.. I close it for now but it might rehappens

**Comment by RELNO** [comment]
Thanks. What is still not clear is why do we send to `ABM` every 3 seconds and not in respect to the changes in grid.

**Comment by agrignard** [comment]
Yes now I send always I have to implement the hash check

Which hash should I check? this one?

`````
https://cityio.media.mit.edu/api/table/grasbrook/meta/hashes/access
`````

**Comment by RELNO** [comment]
> Which hash should I check? this one?

@doorleyr can you advise?

**Comment by RELNO** [comment]
no data in brackets.

**Comment by agrignard** [comment]
I close this issue for now as it seems to appear after a certain time. I am continuing investing this
