### ISSUE TITLE
General Activity Simulation

### ISSUE THREAD

**Issue by wangcan1213** [CityScope/CS_Simulation_GAMA#73]
Following this issue
CityScope/CS_Mobility_Service#30

Some modifications were made to MicroSimulationFromMacroMobilityModel.gaml (branch: activity-simulation-dev ). It will read OD objects from CityIO and simulate general activities. The main difference from the former version is that now each agent is not an unique person, but an unique OD, and multiple agents may refer to the same person.The code will initialize all OD agents at the beginning, but most of them are set as inactive and thus not displayed. An OD agent will be activated when the simulation time reaches the "start_time", and will be deactivated and killed when it comes to "stay_until_time", which is the start time of the next activity for the same person.  Note that a person's activity schedule would be stacked end-to-end in a sense that he will repeat all these activities the next day. If the "stay_until_time" of an OD is in the next day (smaller number of seconds compared to "start_time"), it will be adjusted to 23:59:59.

Some new attributes for "people" species:
origin: origin of the OD, i.e. place of the last activity
desti: destination of the OD, i.e. place of current activity
start_time: what time to move from origin to destination
stay_until_time: until what time the agent will stay at the destination, actually the start_time of the next activity for the same person
mode: one of driving/cycling/walking/pt for the OD
active: if the simulation time lays in [start_time, stay_until_time], the agent is active and displayed
activity: one of 12 types of activities, i.e. home, work, school, drop-off, buy groceries, buy services, eat, recreation, exercise, visit friends, hospital , religion.
trip_type: one of 3 types of trips, i.e. HBW (home based work), HBO (home based others), NHB (non home based)
from_portal: if the origin of the OD is actually a portal, external time would be added to start_time.
to_portal: if the destination of the OD is actually a portal, the agent would be killed immediately when arriving at the portal; otherwise the agent would do move_pedestrian reflex until stay_until_time

**Comment by agrignard** [comment]
I close this issue for now as this model is not in use anymore
