### ISSUE TITLE
Some agents are stuck at their origins

### ISSUE THREAD

**Issue by wangcan1213** [CityScope/CS_Simulation_GAMA#74]
When running MicroSimulationFromMacroMobilityModel.gaml, some agents are stuck at their origins and do not move throughout simulation. This issue keeps emerging in different versions of codes.

A simple visualization shows that most of these problematic agents are related to a specific portal. 
In the following image, only agents with real_speed=0 are displayed, with white circles representing their real time location, and colored lines with arrows representing their origins and destinations. A red line means moving into the area from a portal (from_portal=1, to_portal=0), a blue line means moving outside to a portal (from_portal=0, to_portal=1), and a green line means moving inside the area (from_portal=0, to_portal=0). Obviously, all arrows are related the portal at the northwest corner, and the agents are just stopping at their origins.
![stuck1](https://user-images.githubusercontent.com/51176261/70661182-bb535f80-1c31-11ea-902e-aae93a51b9a6.png)

The following image shows the mode map at that time. Problematic agents moving outside (blue lines in the image above) are high lightened. Noticing they are so close to road segments, the issue shall not be attributed to that the network cannot find a way from origin to destination.
![stuck2](https://user-images.githubusercontent.com/51176261/70662835-091d9700-1c35-11ea-9cea-e3c6834d160a.png)

With more agents entering, the number of stuck agents increases. Most of them are still related to that portal, but other portals could be involved too. 
![stuck3](https://user-images.githubusercontent.com/51176261/70663155-bee8e580-1c35-11ea-9454-80bdc1c6aa44.png)

**Comment by agrignard** [comment]
Won"t be fix soon
