### ISSUE TITLE
Perform keystoning for Aalto ABM

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_Simulation_GAMA#75]
@sannailtanen the keystoning can be performed by changing the 'camera_pos' and 'camera_look_pos' parameters of either/both displays.

camera_pos is where the camera is looking from and camera_look_pos is where the camera is looking at. So camera_pos should be placed somewhere 'above' camera_look_pos. You can play with the x and y values of both to change the position/angle of viewing and adjust the z value of camera_pos to change the zoom level.

@agrignard let us know if this isn't the best way to keystone. I saw in [this issue ](https://github.com/gama-platform/gama/issues/2174) that there is a keystoning feature but you seem to prefer using the camera position parameters.

@sannailtanen Please do the keystoning and commit your changes.

**Comment by agrignard** [comment]
The keystone can be performed by moving the camera and then saving the position with the copy facets from the side controls but there is also a dedicated embedded keytone in GAMA 

More details can be found in the Gama Documentation here:
https://gama-platform.github.io/wiki/Displays

To trigger the keystone:
1. Be sure to be in a opengl mode
2. Launch the simulation and  Press K to trigger the keystoning
4. Clic in one of the corner to perform the keystone
5. Recclick ones to disable the keystone
6. Do it for the four corners
7. Save the desired keystone pressing on the side controls on the top right corner of the simulation
and then in the Keystone menu press copy as facets and finally write this part of the code in the display 
<img width="1207" alt="Screen Shot 2020-02-10 at 14 55 28" src="https://user-images.githubusercontent.com/3928502/74156118-fd8b2400-4c15-11ea-96db-a8d65f90b88a.png">

@sannailtanen let us know how it goes and do not hesitate to ask for help on this specific issues

**Comment by doorleyr** [comment]
@sannailtanen I just updated the model so that the camera is rotated by 45 degrees. You can adjust the rotation parameter if this still isn't right. I suggest trying to get as close as possible by using the camera and rotation parameters in the code. You can then use the keystone method to fine tune and copy those fine tuned parameters into the code as described by @agrignard  .

@agrignard I tried using the keystone feature myself but I couldn't figure out how to bring up the side control shown in your screenshot. How do you bring this up?

**Comment by agrignard** [comment]
I think this is fixed now. I close it for now @sannailtanen feel free to repen it if needed
