### ISSUE TITLE
Repo Cleaning: Activity Simulation Dev

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#78]
@wangcan1213 are you still working on this branch? I think it was an attempt but I am not sure if it's still alive?

https://github.com/CityScope/CS_Simulation_GAMA/tree/activity-simulation-dev

If it's ok for you I might archive this branch, let me know

**Comment by wangcan1213** [comment]
@agrignard  I am not working on it right now, but can we archive it later? As Ronan said, we may need to use Gama for scenario-based model.
