### ISSUE TITLE
Restarting the Economy

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#79]
It could be good to start modeling how the different safety measures (Masks, globs, social distance, cleaning working surfaces, quarantine, etc. are impacting to the sprawl of the Pandemic and how can we implement them in Countries getting out of the alert in order to get "back into ""Normal"" "

**Comment by agrignard** [comment]
Some pretty good steps have been made these last days in this topic (please feel free to run it and give me your feedback!)

For that Just open GAMA (be sure to have the 1.8 version) update this repo and run this model

`````
CityScope_Coronaizer.gaml
`````
 (https://github.com/CityScope/CS_Simulation_GAMA/blob/master/CS_CityScope_GAMA/models/CityScope_Coronaizer.gaml)

Then you have 3 main experiment

1. ````Coronaizer```` run one volpe model 
2. ````CityScopeMulti```` will run n times the volpe model but you can play with the parameter like infection rate etc
3. ````CityScopeMutliCity```` will run a model on different cities.

Ones the model is run this is how to look the interface where you can play with the different parameters and display different information such as heatmap, infection graph etc.

As always it's a work in progress but the tool is working pretty well to understand the spreading and the policy, it would be great if @LAAP but also other reading this issue can run it and give there feedback one what can be improved. Also a great next step would be to run it on "real" data like the cuebiq ones.

Let me know what you think

<img width="1919" alt="Coronaizer" src="https://user-images.githubusercontent.com/3928502/78807804-dd34d700-79c4-11ea-9dd0-44feee01afba.png">

**Comment by agrignard** [comment]
see more specific issues
