### ISSUE TITLE
Flattening the Curve

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#80]
Looking great, I will play with it. 

I have few preliminary thoughts: in order to model the Flattening of the Curve effect maybe we can add as a variable:

- Number of urgent medicalized beds in hospitals

- Number of medical staff (doctors, nurses, etc)

**Comment by agrignard** [comment]
Oh yeah now we are talking totally agree. This initial attempt is litterally to plug a SIR on any existing model like the volpe (but can be anyone, Guadalajara, andorra, lyon etc) but yes for sure then we need to dig it and make a dedicated model. Right now the Infected people keep on doing there life which is indeed not realistic at all ;-)!

**Comment by LAAP** [comment]
It is a very good step. Let's work on defining the behaviour of infected people. Symptomatic, asymptomatic, critical state, quarantined, etc.

**Comment by agrignard** [comment]
see more atomic issues

**Comment by LAAP** [comment]
Yes. Exploring this issues can help a lot
