### ISSUE TITLE
Gathering the input and output data in a CSV file

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#83]
In order to have a way of comparison between the different simulation runs, it could be good having a way of gathering the input and output data in a CSV file that saves automatically in a folder.

**Comment by agrignard** [comment]
See Library models/Data Exportation/Save to CSV.gaml or here to see how to make it

I did a simple export here (just put savetoCSV to true) 

`````
	
reflex save_model_output when: every(#day) and savetoCSV{
  save [time,nb_susceptible,nb_infected, nb_recovered, nb_death] to: filePathName type:"csv" rewrite: false;
}
`````
