### ISSUE TITLE
Can't Find "Autonomous_Covid_Community.gaml" in the cloned repo

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#85]
Sorry for being the "dome kid" here @agrignard , but I can't Find "Autonomous_Covid_Community.gaml" in the cloned repo:

<img width="1440" alt="Captura de pantalla 2020-04-23 a las 14 48 11" src="https://user-images.githubusercontent.com/19315213/80137978-1f881780-8572-11ea-89ff-1a06023d4eb6.png">

**Comment by agrignard** [comment]
haha how to be more precise...

It s in the github so you have something wrong with your settings

Did you pull ? are you pulling on the right branch? do you have internet ? ;-) more seriously:

-Why you mention cloning the repo, you have this repo for a while no? In any case cloning/pulling/grabbing/tomar, what is important is to get the last version which is a commit from today on the master branch. I even made a special one just for you the last commit is called "Special just for Luis" that you can see in your github desktop

<img width="1920" alt="Screen Shot 2020-04-23 at 22 18 49" src="https://user-images.githubusercontent.com/3928502/80145432-74e31980-85b0-11ea-88b7-3d19a27b4143.png">

-Are you sure you CityScope_GAMA is pointing to the right Github (to check that right clik on the CityScope_GAMA folder and then left click on "Reveal in OS")

-If you answer yes to all of this, the resatart GAMA, create a new worskpace and reimport the CityScopeGAMA rpeoject from the Gthub

**Comment by LAAP** [comment]
Finally, I made it.

As a first step it is very cool. Let me play a bit and then I will make my "Santa" list
<img width="1440" alt="Captura de pantalla 2020-04-24 a las 11 35 27" src="https://user-images.githubusercontent.com/19315213/80230353-d55d6f80-861f-11ea-8f3f-e9983310369f.png">
