### ISSUE TITLE
Autonomous_Covid_Community model

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Simulation_GAMA#86]
@agrignard , great job! the Autonomous_Covid_Community model is a crazy good starting point

After playing with the model a bit, I have some suggestions:

**-Agent's behavior:**
The difference of the agent's behavior-output between "Autonomy" and "Conventional" needs to be more clear. Now both scenarios looks like very similar:

<img width="1440" alt="Captura de pantalla 2020-04-24 a las 14 47 51" src="https://user-images.githubusercontent.com/19315213/80246580-a43e6880-863a-11ea-8f03-aa3b4115cc5e.png">

<img width="1440" alt="Captura de pantalla 2020-04-24 a las 14 47 59" src="https://user-images.githubusercontent.com/19315213/80246602-ab657680-863a-11ea-861e-e5039717c310.png">

**Differences:**

_1) In "Autonomous" world: Big internal flow "Inside the cells", but very little "between cells"

_2) In "Conventional world: Big external flow "between cells", very little "inside cells"

**Common elements:**

_1) Behavior: In both "worlds", agents need to have the same behavior, however, due the 2-different urban designs the output will be different. The behavior is a loop from:

_home-work-shopping-home_

_2) Time:_ Since it is a cyclical behavior, the agents will move all together (minus -10% random behavior and -5% of people working at home) from "home-work-shopping-home"

_3) Dots:_ The "tails" are the important part, not the “dots”, So: Smaller and more transparent dots. More diversity of agents (color)?

4) Design and colors: That will be a new issue for latter

**-Outputs:**

It could be good to measure to have some mathematical outputs:

**I) EFFICIENCY OF THE CITY:**

a) Number of trips = Walk (inside the cell) versus Mass transportation (Between cells)

b) Working time = Number of agents working and achieving the goal of working from home or at the office

c) Environmental impact = % of trips between cells versus walking trips 

The sum of these 3 parameters will give us an “Energy-bar indicator” named “Efficiency of the city

**II) PANDEMIC IMPACT:**

a) Number of infections

b) Number of deaths (?)

c) Number of recoveries (?)

d) Number of occupied beds in Hospitals(?)

**Comment by agrignard** [comment]
Thanks for your input @LAAP so let me answer to some of this request and break it down in more atomic issues

> @agrignard , great job! the Autonomous_Covid_Community model is a crazy good starting point
> 
> After playing with the model a bit, I have some suggestions:
> 
> **-Agent's behavior:**
> The difference of the agent's behavior-output between "Autonomy" and "Conventional" needs to be more clear. Now both scenarios looks like very similar:

See this issue https://github.com/CityScope/CS_Simulation_GAMA/issues/87

-------------------------------------------------------------------------------------
> 
> <img alt="Captura de pantalla 2020-04-24 a las 14 47 51" width="1440" src="https://user-images.githubusercontent.com/19315213/80246580-a43e6880-863a-11ea-8f03-aa3b4115cc5e.png">
> 
> <img alt="Captura de pantalla 2020-04-24 a las 14 47 59" width="1440" src="https://user-images.githubusercontent.com/19315213/80246602-ab657680-863a-11ea-861e-e5039717c310.png">
> 
> **Differences:**
> 
> _1) In "Autonomous" world: Big internal flow "Inside the cells", but very little "between cells"
> 
> _2) In "Conventional world: Big external flow "between cells", very little "inside cells"

See this issue https://github.com/CityScope/CS_Simulation_GAMA/issues/88

-------------------------------------------------------------------------------

> 
> **Common elements:**
> 
> _1) Behavior: In both "worlds", agents need to have the same behavior, however, due the 2-different urban designs the output will be different. The behavior is a loop from:
> 
> _home-work-shopping-home_
> 
Is this an issue? Can you be more specific?
> _2) Time:_ Since it is a cyclical behavior, the agents will move all together (minus -10% random behavior and -5% of people working at home) from "home-work-shopping-home"

I don't understand this one either

> 
-----------------------------------------------------------
> _3) Dots:_ The "tails" are the important part, not the “dots”, So: Smaller and more transparent dots. More diversity of agents (color)?

See this issue https://github.com/CityScope/CS_Simulation_GAMA/issues/89

----------------------------------------------------------

> It could be good to measure to have some mathematical outputs:
> 
> **I) EFFICIENCY OF THE CITY:**
> 
> a) Number of trips = Walk (inside the cell) versus Mass transportation (Between cells)
> 
> b) Working time = Number of agents working and achieving the goal of working from home or at the office
> 
> c) Environmental impact = % of trips between cells versus walking trips
> 
> The sum of these 3 parameters will give us an “Energy-bar indicator” named “Efficiency of the city

See this issue https://github.com/CityScope/CS_Simulation_GAMA/issues/90

----------------------------------------------------------------

> **II) PANDEMIC IMPACT:**
> 
> a) Number of infections
> 
> b) Number of deaths (?)
> 
> c) Number of recoveries (?)
> 
> d) Number of occupied beds in Hospitals(?)


See this issue https://github.com/CityScope/CS_Simulation_GAMA/issues/91

**Comment by LAAP** [comment]
Ok perfect! Thank you @agrignard

**Comment by LAAP** [comment]
Since, now it is divided, I am closing this issue
