### ISSUE TITLE
Differentiate Conventioanl Zoning and Autonomy

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#87]
Conventional: Every usage is in one specific district
Autonomy: each district has 3 usages

One thing could be to differentiate the color of the district in the conventional scenario to see that every district has a specific function

**Comment by LAAP** [comment]
@Arnaud, this is difference needs to emerge from the simulation. 

However, I think that it is good idea to have a colored outer thick circle per district matching with the use in the conventional scenario, and this circle is the same color in the autonomous one

**Comment by agrignard** [comment]
<img width="1290" alt="Screenshot 2020-04-27 at 12 00 27" src="https://user-images.githubusercontent.com/3928502/80359856-bd375b80-887e-11ea-827a-c7104244c8f9.png">

<img width="1301" alt="Screenshot 2020-04-27 at 12 00 38" src="https://user-images.githubusercontent.com/3928502/80359881-c7f1f080-887e-11ea-811b-947fa7da317e.png">

**Comment by agrignard** [comment]
@LAAP you can play with the color of the autonomy with the variable (so far a clear blue)
````
autonomousDistrictColor
````

**Comment by LAAP** [comment]
@agrignard thanks! Do you mean "playing with the color in the code", isn't?

**Comment by agrignard** [comment]
yes this is the variable to change the color (or you can also propose some from Photohop, it's classical rgb values)

`````
autonomousDistrictColor
`````
