### ISSUE TITLE
Differentiate macro mobility and micro mobility

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#88]
- In "Autonomous" world: Big internal flow "Inside the cells", but very little "between cells"
- In "Conventional world: Big external flow "between cells", very little "inside cells"

**Comment by agrignard** [comment]
the ratio can be changed by using this variable (currently 0.1)
`````
crossRatio
`````

and now macro trip are displayed as a square and micro as a circle

**Comment by LAAP** [comment]
@agrignard , Ok. It could be good to understand a bit this "crossRatio" variable: 

If I have 0.04 it is "almost" working as I was expecting in Autonomous communities (very similar than Conventional).

<img width="1440" alt="Captura de pantalla 2020-04-27 a las 15 17 18" src="https://user-images.githubusercontent.com/19315213/80412019-2af18080-889b-11ea-8d5c-3d518b8d10d2.png">

But, when I shift into Conventional, the conventional is still looking like the "autonomous community"... Why people move in the residential cell that much? I can understand, maybe, people moving and going to all the shops, but people doesn't visit all the houses of his district. Same thing with the office. I think that the activity inside of the cells in the conventional, needs to be less intense than in the autonomous. Also, the commute needs to be shown "thicker", so maybe you let the agents using a "thicker line" to sprawl when they commute in this mode

<img width="1440" alt="Captura de pantalla 2020-04-27 a las 15 16 51" src="https://user-images.githubusercontent.com/19315213/80411986-1f05be80-889b-11ea-89f9-1ba54024353e.png">

**Comment by agrignard** [comment]
The crossRatio is the ratio of people that will commute from district to district in the autonomy mode. 

So if you put 0.04 you will have 4% of the people commuting through district and 96% staying in their district (assigned randomly for now)

The behavior of this people in this model is ultra simple=> home->shopping->Business in a loop. So in the conventional scenario they are not visiting several houses, you have the impression that they are doing so because they have the same color and so on. I will do a version with random color do differentiate all the people it will be easier to track each of them.

**Comment by LAAP** [comment]
@agrignard , some questions: Are the same "people agents" going always to the same "House agent" and the same "office agent"? That could be important in the model. "shops" can be more random.

Please, Don't do random color, do a scale (palet) of bluish

**Comment by agrignard** [comment]
right now they have one residential , one shop and one businnes, but ys it could make sens to have for instance several shops

**Comment by LAAP** [comment]
@agrignard , In other Issue we were talking about having 1 or 2 models. I think that multy scenario is cool but should be for "comparing" the 2 scenarios, and that maybe a next step and a lot of work and thinking, How do we compare them? 

Maybe having 2 separated models makes more sense

**Comment by agrignard** [comment]
Close this issue for now. More specific ones can be created
