### ISSUE TITLE
Add transparency slider for Viral People

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#92]

**Comment by agrignard** [comment]
Ok you can play with Viral People transparency now (not sure it's a must but it's here)

**Comment by LAAP** [comment]
@agrignard , In the new MultyScenarios model, this tags are "gone". Is the MultyScenarios model the future unified model?

**Comment by agrignard** [comment]
I think the multi scenarios will be removed

**Comment by LAAP** [comment]
Awesome @agrignard !

**Comment by agrignard** [comment]
OK so I take this "awesome" asa request to remove the multi scenario?

**Comment by LAAP** [comment]
Hi @agrignard , 
I think we are not understanding each other with "models", "scenarios", etc. Sorry for my lack of lexico in computer science.

What I think that we need is: running once Gama, and having, in the same "project", a tag that changes from autonomous to conventional, as it was, but that every time that you change it, it resets the "experiment".

**Comment by agrignard** [comment]
I think this is the current behavior (updated this morning) every time you change between conventional and autonomous the simulation restart

**Comment by LAAP** [comment]
Perfect @agrignard
