### ISSUE TITLE
Autonomy Vs Conventional:

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#95]
I think that it is confusing to have a tag that jumps from the scenario of Autonomy to Conventional without re-starting the simulation. Either we restart the simulation with that tag, or we rune both simulation at the same time and we visualize one or the other with the tag.

**Comment by agrignard** [comment]
I just add a new experiment called MultiScenarios with the 2 scenarios in //
<img width="1920" alt="Screenshot 2020-04-30 at 11 50 00" src="https://user-images.githubusercontent.com/3928502/80697109-ca4f8700-8ad8-11ea-9860-f09ab57f56ba.png">

**Comment by LAAP** [comment]
Hi @agrignard ,

Great! There are some issues:

1) Now we are missing the Graph with infected people etc.

2) The speed of the simulation, only affects to the autonomous scenario (the graph in the right):

<img width="1440" alt="Captura de pantalla 2020-04-30 a las 13 14 45" src="https://user-images.githubusercontent.com/19315213/80739506-94180480-8ae4-11ea-96f9-1c5b24ee10bc.png">
 


3) When you change the tag from Conventional or autonomy and vice versa, only affects the to the scenario in the right:


<img width="1440" alt="Captura de pantalla 2020-04-30 a las 13 11 31" src="https://user-images.githubusercontent.com/19315213/80739691-db9e9080-8ae4-11ea-8055-ede9af41a03a.png">


I suggest either keeping just the autonomous scenario with the tag, or the 2 scenarios and eliminate the tag

**Comment by agrignard** [comment]
The problem here that  i d'int think about before to rpopse youa multi experiment  is related to the way GAMA is made:  any parameters only have an impact on the last (so the current) describe the experiment. So I don't think it's the right solution to have two experiments here . 

The question is do we need two experiment in // or can't we produce 2 videos? In that case it's 2 separated experiment.

**Comment by LAAP** [comment]
Hi @agrignard ,

I think that there are 2 options:

1) 2 experiments in the same model, that shifts from one to the other (visually but also computationally) son they run only when the "autonomy tag" is on or off, so they restart everything when you play with the "tag". In this option, maybe the "infection Graph" can stay as a benchmark in a very light color in the back, so you can see the difference between 1 model and the 2nd

2) Two separate models. I think that this is the easier one

Both options are good to me

**Comment by agrignard** [comment]
Sorry, I don't understand the issue here and I think we do'nt have the same definition of model and experiments. The first option that you mention here  is what was already implemented here. When you run the model you have a button (Is this what you call "tag"?) to switch between conventional and autonomy 

The option 2 doesn't make sense for me to have 2 separate models are the 2 models are very similar

**Comment by agrignard** [comment]
Going back to the beginning with only one scenario...
