### ISSUE TITLE
Hospital Policies 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#96]
A) Generic numbers:

We need to find the ratio of people using a hospital bed because of this pandemic: between 15 days and 35 days? (Maybe this is a slider?)
We need to find the latest data about % of infected people who needs a normal bed, a medicalised bed, or goes asymptomatic
We need to find the number of medicaliced beds per hospital: between 5 and 20? (other slider?)
We need to find the number of normal beds in hospitals: between 50-100-200? (other slider?)
We need to find the ratios of people passing away when they have no access to hospitals versus when they have access to hospitals
B) Scenarios:

-Common setting: Maybe we have a centralized general Hospital in the Business district (Conventional) and in the Low-right circle (Autonomous) with "X" number of beds (slider) and "Y" number of medicaliced beds (slider)

-Conventional: People gets sick and after 15 days (more or less), the symptomatic (a " X" %) goes to the hospital, the very sick goes to the medicalized bed, the normal sick goes to a normal hospital bed where they recover faster than at home, and reduces the chance to go to a medicalized bed. The people recovering from a medicalized bed, they go after to a hospital bed, and when they are fully recover, goes back to normal.

If the hospital gets overflowed, people stay at home without care (the illness goes faster and more chance to get worse and of passing away), and only goes to the hospital when happens to have a vacant bed (passed away of recovered).

-Autonomous: We have the same hospital than conventional, and the process/protocol of illness is the same than in the conventional. However, people has at home "robotic sensitized houses" that takes care of you in the low level of infection, it takes care of you like in a "normal bed of the hospital" and sends you to the hospital as soon as you get worst (increasing your chance of surviving)

In this case, I think that the hospital will not get overwhelmed in the normal beds, but yes in the medicalized... But if the "quarantine made district by district" is efficient, maybe the impact is lower... That is what we are interested din finding

**Comment by agrignard** [comment]
Start to had the hospital concept
<img width="253" alt="Screenshot 2020-05-11 at 12 48 41" src="https://user-images.githubusercontent.com/3928502/81553656-c697ec00-9385-11ea-9335-2efdbccdbfe1.png">

**Comment by LAAP** [comment]
Awesome @agrignard !
It could be cool to have 2 options for the Hospital (a tag):

1) Hospital "inside of one Community"

2) Hospital, as a "4th" element to commute, "Outside of the communities"

**Comment by agrignard** [comment]
See #132
