### ISSUE TITLE
CityScope_Coronizer model

### ISSUE THREAD

**Issue by maitaneiruretagoyena** [CityScope/CS_Simulation_GAMA#98]
Hi @agrignard! The model is great! Maybe @LAAP and you talk about this, but I have some comments regarding the MultiScenarios experiment:

- Should we add some shared amenities outside the communities? Like hospitals, schools... that are used by more than one community. 
- I think @LAAP talked about this, but it could be good to have some diversity of agents. The dots are really small to differentiate the color, but maybe we can change the color/type of line of the trajectory?

Good job!

**Comment by LAAP** [comment]
@agrignard , I think @maitaneiruretagoyena is correct, Having hospitals to see the recovery process was already in my first issess, and it can help a lot

**Comment by agrignard** [comment]
Thank you @maitaneiruretagoyena for your input. 

_Should we add some shared amenities outside the communities? Like hospitals, schools... that are used by more than one community._

Why not we just need to agree on which one and then respecifi the behavior of people which for now Home, Shopping, Business.

And for the hospital this is in this issue
https://github.com/CityScope/CS_Simulation_GAMA/issues/96

_-I think @LAAP talked about this, but it could be good to have some diversity of agents. The dots are really small to differentiate the color, but maybe we can change the color/type of line of the trajectory?_

Right now they are all the same kind of agent but all using a different color of blue that coudl represent something. So yes it's possible but what kind of profile do we want to show.

**Comment by agrignard** [comment]
See #96 and #99
