### ISSUE TITLE
Profile of Agent

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Simulation_GAMA#99]
@LAAP and @maitaneiruretagoyena what is the type of profile of Agent you are thinking of?

**Comment by LAAP** [comment]
@agrignard ,

We have several options for profiles, and the visualization can be a mix of them :

**1) Visualizing the "adoption of health and safety measures"** (Physical distance, mask, etc) So light blue (or other color) is 0 measures, darker color y the agent taking more and more measures until 100%, then, we could have a visual indicator of number of people taking the measures, and correlation with infection.

**2) Visualizing working/life behaviour.** We can start with a simple 3 types of people: People that works from home, people working in the office, people working in shops. All the agents has 5 time steps:

-People that works from home:   _Home - Home - Shopping - Home - Home_
-People working in the office:    _Home - Work - Shop - Work - Home_
-people working in shops:    _Home - Shop - Shop - Shop - Home_

**3) Visualizing the pandemic:** This is almost there. We can have: Healthy, Sick asymptomatic, Sick symptomatic, Death, recovered.

-Healthy: Moves as point 2 (color: bluish) 
-Sick asymptomatic: Moves as point 2, infecting people (with the arc showing infection, as you have it already in the model) (color: red) 
-Sick symptomatic: From wherever it is to Hospital. if hospital is full, then goes back home, and stays home until either dies or recovers, but infecting people living with him, and maybe going shopping once every 7 circles (for food) (color: orangish) 
-Death: The person stops and gets black wherever it is (color: black) 
-Recovered: Moves as point 2 (color: green)

**Comment by agrignard** [comment]
_1) Visualizing the "adoption of health and safety measures" (Physical distance, mask, etc) So light blue (or other color) is 0 measures, darker color y the agent taking more and more measures until 100%, then, we could have a visual indicator of number of people taking the measures, and correlation with infection._

=>First attempt an aspect (dark blue= noting , blue= mask or quarantine; light blue = mask / quarantine) has been added to do so. So far there is two aspect ````health```` and  ````safety_measures````. The question ow is how to we want to trigger it
<img width="945" alt="Screenshot 2020-05-06 at 10 11 08" src="https://user-images.githubusercontent.com/3928502/81152222-0aec4c00-8f82-11ea-8c79-3069983a7b0e.png">


``````
	aspect safety_measures{
		if(showPeople ){
		  if (!as_mask and !target.isQuarantine){
		    draw circle(5#m) color:rgb(0,0,125) border:rgb(0,0,125)-100;	
		  }
		  if (as_mask xor target.isQuarantine){
		    draw circle(7#m) color:rgb(70,130,180) border:rgb(70,130,180)-100;	
		  }	
		  if(as_mask and target.isQuarantine){
		    draw circle(9#m) color:rgb(135,206,250) border:rgb(135,206,250)-100;		
		  }
		}
	}
``````

**Comment by agrignard** [comment]
_2) Visualizing working/life behaviour. We can start with a simple 3 types of people: People that works from home, people working in the office, people working in shops. All the agents has 5 time steps:

-People that works from home: Home - Home - Shopping - Home - Home
-People working in the office: Home - Work - Shop - Work - Home
-people working in shops: Home - Shop - Shop - Shop - Home_

I am ok to work on that but this behavior is not in the model. So before to put it on the model we need to be sure that this is worth as it might complexify the story telling

**Comment by agrignard** [comment]
_3) Visualizing the pandemic: This is almost there. We can have: Healthy, Sick asymptomatic, Sick symptomatic, Death, recovered.

-Healthy: Moves as point 2 (color: bluish)
-Sick asymptomatic: Moves as point 2, infecting people (with the arc showing infection, as you have it already in the model) (color: red)
-Sick symptomatic: From wherever it is to Hospital. if hospital is full, then goes back home, and stays home until either dies or recovers, but infecting people living with him, and maybe going shopping once every 7 circles (for food) (color: orangish)
-Death: The person stops and gets black wherever it is (color: black)
-Recovered: Moves as point 2 (color: green)_

See #103

**Comment by LAAP** [comment]
> _1) Visualizing the "adoption of health and safety measures" (Physical distance, mask, etc) So light blue (or other color) is 0 measures, darker color y the agent taking more and more measures until 100%, then, we could have a visual indicator of number of people taking the measures, and correlation with infection._
> 
> =>First attempt an aspect (dark blue= noting , blue= mask or quarantine; light blue = mask / quarantine) has been added to do so. So far there is two aspect `health` and `safety`. Then a power bar on the right to show the KPIs
> 
> <img alt="Screenshot 2020-05-06 at 10 26 25" width="1483" src="https://user-images.githubusercontent.com/3928502/81154392-248e9300-8f84-11ea-97ad-b6aefa9cfa0d.png">

@agrignard This is looking great! Very good job! I like the direction that this is taking. I also like the change of diameter of the agents depending on their behaviour. 

One question: I see in the "safety level KPIs" 2 levels Mask and Quarantine, but you have 3 levels (3 colors) of people. I assume that the dark blue will be people keeping the physical distance, isn't? It could be good to have like a "blinking light/transparent" 2m-distance circle around this guys. Some examples from internet:

![maxresdefault](https://user-images.githubusercontent.com/19315213/81181295-3ec37380-8f7a-11ea-9634-f5d4e4c35530.jpg)

![images](https://user-images.githubusercontent.com/19315213/81181308-46831800-8f7a-11ea-8afc-59273527775a.jpeg)

![1](https://user-images.githubusercontent.com/19315213/81181338-50a51680-8f7a-11ea-9c9b-cccda2366de3.jpg)

**Comment by agrignard** [comment]
The keeping distance is unfortunately not implemented yet as it's much more difficult that it seems to be. right now there is mask and quarantine, however, i can use your circle over circle appraoch to have like small circle= nothing, 2 cricle= mask, 3 circle = mask+quarantine

**Comment by agrignard** [comment]
Could be something like that but not super easy to understand
<img width="1078" alt="Screenshot 2020-05-06 at 15 23 37" src="https://user-images.githubusercontent.com/3928502/81182032-95967080-8fad-11ea-82d7-67a311c26a4c.png">

**Comment by LAAP** [comment]
Hi @agrignard ,

Yes, I think the circle is working, but let's keep only one version, maybe this one: 

![1111](https://user-images.githubusercontent.com/19315213/81198156-26aa1f00-8f8f-11ea-8021-e4bfa664135a.jpg)

**Comment by agrignard** [comment]
but this is not for social distance, this is to show who is using mask and quarantine, it looks cool but I don't think it works for this purpose (showing mask and quanrantine)

**Comment by LAAP** [comment]
@agrignard ,

I think that we should keep the agents as they use to be in your first image of today , Without outer circle:

<img width="402" alt="2222" src="https://user-images.githubusercontent.com/19315213/81240260-e5d4f900-8fd4-11ea-83b9-0fe4fdbf409e.png">

 The information will came from the color and diameter of the agent, like in the image :

- Nothing = Normal blue, and normal diameter of the circle
- Mask = Darker blue, and a bit smaller the circle
- Quarantine + Mask = Light blue, and bigger diameter of the circle (fat-quarantine-guy)

extra:

- Social distance = all of the above but with the outer circle that I have mentioned  (Outer circle = representation of the social distance). As an example, this image that is Mask+Social distance:

![1111](https://user-images.githubusercontent.com/19315213/81240409-5714ac00-8fd5-11ea-946e-1de1cc46a7e3.jpg)


Please, let me know your thoughts

**Comment by agrignard** [comment]
Closing this one. If there is a more specific one don not hesitate to reopen another one

**Comment by LAAP** [comment]
I am reopening this issue due several issues, @agrignard:

1) In the model all the agents are now "green". Not division by color and profile

2) I like the "yellow dot" as a mask, Can we have also an other circle for social distancing?

3) When people commute our, can we show a "identification"? In previous models they become "rectangles". Maybe it is too much, not sure, but maybe they can have an outer circle or an outer rectangle or something that identify the commute moment?

**Comment by agrignard** [comment]
By defaut you see the heatly mode that's why they are gree for (S) and then turn to Red if infeced.

If you press on "p" then you get the profile aspect and "s" the safety aspect

**Comment by LAAP** [comment]
Great @agrignard! It is looking good. 

However, now we have "p", "s", "I".... Can we have instead of a keyboard entry some "tags or buttons", or , at least a "dictionary" or ?

**Comment by LAAP** [comment]
Hi @agrignard ,
Regarding the color. Now infected people (red) doesn't shift into "inmune", So we do never see recovered people... But also we do not have death people any more....

**Comment by agrignard** [comment]
Yes you're this is due to the recovery time which is to high. I have to work a bit on that value

Once it's done you can play with it and find the "right" value, that can be useful.

**Comment by agrignard** [comment]
see #116

**Comment by LAAP** [comment]
Awesome! Thanks!
